force-app/main/default/objects/DiscountCoupons__c/DiscountCoupons__c.object-meta.xml
<CustomObject>
    <label>Discount Coupons</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Discount Coupons Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DiscountCoupons__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic Coupon for First WO</fullName>
            </value>
            <value>
                <fullName>Generic Coupon for specific time</fullName>
            </value>
            <value>
                <fullName>Specific to a student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount  Percent/Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/DiscountCode__c.field-meta.xml
<CustomField>
    <fullName>DiscountCode__c</fullName>
    <formula>Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/eTutorUserID__c.field-meta.xml
<CustomField>
    <fullName>eTutorUserID__c</fullName>
    <formula>Contact__r.eTutorUserID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>eTutorUserID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <label>ExpiryDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Plagiarism</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentEmail__c.field-meta.xml
<CustomField>
    <fullName>StudentEmail__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentNameFormula__c.field-meta.xml
<CustomField>
    <fullName>StudentNameFormula__c</fullName>
    <formula>Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentNameFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentPhone__c.field-meta.xml
<CustomField>
    <fullName>StudentPhone__c</fullName>
    <formula>Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentPhone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiscountCouponTriggerHelper.cls
public class DiscountCouponTriggerHelper {
    public String assignmentRecordTypeID;
    
    public DiscountCouponTriggerHelper()
    {
        
    }
    
    
    
    
    public void sendDiscountCouponsNotificationsToCustomer(List<DiscountCoupons__c> newList,Map<ID,DiscountCoupons__c> oldMap)
    {
        List<String> receiver = new List<String>();
        
        For(DiscountCoupons__c dc: newList)
        {
            IF(dc.Service__c.equalsignorecase('Assignment') ||dc.Service__c.equalsignorecase('Plagiarism')  )
            {
                try
                { 
                    Boolean sendToETutor=false;
                    Boolean sendSMS =false;
                    String SMSMessageTemplate;
                    DiscountCoupons__c oldWo = new DiscountCoupons__c();
                    If(oldMap!=null)
                     oldWo = oldMap.get(dc.id);
                    receiver.add(dc.StudentEmail__c);
                    If( dc.category__c.equalsignorecase('Generic Coupon for First WO') || dc.category__c.equalsignorecase('Generic Coupon for specific time'))
                    {
                       
                    IF ((Trigger.isUpdate && oldWo!=null && dc.Status__c.equalsignorecase('Active') && !oldWo.Status__c.equalsignorecase('Active')) || (Trigger.isInsert && dc.Status__c.equalsignorecase('Active')))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorInitialPayment,dc.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='DiscountCoupon';
                        DiscountCouponAllocationTriggerHelper helper1 = new DiscountCouponAllocationTriggerHelper ();
                        
                        // sendDiscountCouponToETutor(dc.eTutorUserID__c,dc.DiscountCode__c,dc.Service__c,dc.Status__c,dc.id,'DiscountCoupon',dc.description__c,String.valueof(dc.Discount_Amount__c),dc.Discount_Type__c,String.valueof(dc.ExpiryDate__c));
                        helper1.sendDiscountCouponToETutor(dc.eTutorUserID__c,dc.DiscountCode__c,dc.Service__c,dc.Status__c,dc.id,'DiscountCoupon',dc.description__c,String.valueof(dc.Discount_Amount__c),dc.Discount_Type__c,String.valueof(dc.Start_Date__c),String.valueof(dc.ExpiryDate__c),dc.category__c);
                        eTutorSMSNotificationsUtility.sendSMS(label.eTutorSMSMagicFromNumber, dc.StudentPhone__c, SMSMessageTemplate,dc.name,dc.id,dc.StudentNameFormula__c,null,null,null);
                    }
                    }
                } 
                catch( System.Exception e) {  
                    System.debug('ERROR: '+ e);  
                    ErrorHandler.logError('DiscountCouponTriggerHelper','sendDiscountCouponsNotificationsToCustomer'+dc.id, e.getMessage(),e.getStackTraceString());
                }
                
            }  
            
        }
    }
    
    
    
    
    
    
    
    
    
}