force-app/main/default/objects/Taxation__c/Taxation__c.object-meta.xml
<CustomObject>
    <label>Taxation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Taxation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxation__c/fields/Ready_to_consider__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_consider__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to consider</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TaxationDataCleanupBatch.cls
global class TaxationDataCleanupBatch implements Database.Batchable<sObject>,Schedulable
{

	global Database.QueryLocator start(Database.BatchableContext BC)
	{
        String query = 'SELECT Id,Ready_to_consider__c FROM Taxation__c WHERE Ready_to_consider__c = false';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Taxation__c> scope)
    {
        if(!scope.isEmpty()){
            delete scope;
        }
    }  
    global void finish(Database.BatchableContext BC)
    {
    }
    global void execute(SchedulableContext SC) {
 	    database.executebatch(new TaxationDataCleanupBatch());
    }
}