force-app/main/default/objects/Case/fields/tx_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>tx_Contact_Email__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/txContactMobilePhone__c.field-meta.xml
<CustomField>
    <fullName>txContactMobilePhone__c</fullName>
    <label>Contact Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/txVisaStatus__c.field-meta.xml
<CustomField>
    <fullName>txVisaStatus__c</fullName>
    <label>Visa Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Taxation.recordType-meta.xml
<RecordType>
    <fullName>Taxation</fullName>
    <active>true</active>
    <businessProcess>Taxation</businessProcess>
    <label>Taxation</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Tx_VisaStatus__c.field-meta.xml
<CustomField>
    <fullName>Tx_VisaStatus__c</fullName>
    <label>Visa Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F1</fullName>
            </value>
            <value>
                <fullName>H1B</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/classes/tx_StudentConsentForm.cls
public  class tx_StudentConsentForm{
    public Contact SelectedContact {get;set;}
    public Contact SelectedContact1 {get;set;}
    public boolean showTenantDetails {get;set;}
    public string studentEmail {get;set;}
    public boolean hideButtons {get;set;}
    public boolean showButtons {get;set;}
   
    public tx_StudentConsentForm(){
        showTenantDetails=false;
        SelectedContact=new Contact();
        SelectedContact1=new Contact();
        Id contactID = apexpages.currentpage().getparameters().get('studentID');
        List<Contact> c=[Select ID,accountid,Name,lastName,firstname,mobilePhone,email,Tx_visaStatus__c from Contact where ID=:contactID];
        List<Case> cas=[select id, status,IsClosed from Case where contactid=:contactID AND IsClosed=False];
        system.debug('**Contact'+c);
        IF(cas.size()>0) showButtons=false;
        else  showButtons=true;
       
        if(c.size()>0)
        {
            SelectedContact.email=c[0].email;
             SelectedContact.mobilePhone=c[0].mobilePhone;
            SelectedContact.Tx_visaStatus__c=c[0].Tx_visaStatus__c;
            SelectedContact1= c[0];
        }
        
    }
    public PageReference cancel(){
        if(showButtons)
        { 
        Case c  = new Case();
        c.recordtypeid=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Taxation').getRecordTypeId(); 
        c.contactID=SelectedContact1.id;
        c.Accountid=SelectedContact1.accountid;
        c.subject= Date.Today().Year() + ' Taxation for - '+ SelectedContact1.name;
        c.origin='Student Consent';
        c.status='Student Consent Rejection';
        c.tx_Contact_Email__c=SelectedContact.email;
        c.txContactMobilePhone__c= SelectedContact.mobilePhone;

        
        Insert c;
        }
        
        PageReference pageRef = new PageReference('/apex/Tx_StudentConsentAcknowledgement');
        pageRef.setRedirect(true);
        return pageRef; 
    }
    
    public PageReference save(){
        
       if(showButtons)
        {   
        Case c  = new Case();
        c.recordtypeid=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Taxation').getRecordTypeId(); 
        c.contactID=SelectedContact1.id;
        c.Accountid=SelectedContact1.accountid;
        c.subject= Date.Today().Year() + ' Taxation for - '+ SelectedContact1.name;
        c.origin='Student Consent';
        c.status='Student Consent Acceptance';
        c.tx_Contact_Email__c=SelectedContact.email;
        c.txVisaStatus__c=SelectedContact.Tx_VisaStatus__c;
        c.txContactMobilePhone__c= SelectedContact.mobilePhone;
        Insert c;
        }
        PageReference pageRef = new PageReference('/apex/Tx_StudentConsentAcknowledgement');
        pageRef.setRedirect(true);
        return pageRef;      
    }
    
    
}