force-app/main/default/objects/Case/fields/tx_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>tx_Contact_Email__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/txVisaStatus__c.field-meta.xml
<CustomField>
    <fullName>txVisaStatus__c</fullName>
    <label>Visa Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Taxation.recordType-meta.xml
<RecordType>
    <fullName>Taxation</fullName>
    <active>true</active>
    <businessProcess>Taxation</businessProcess>
    <label>Taxation</label>
</RecordType>

force-app/main/default/objects/Contact/fields/ReferredStudent__c.field-meta.xml
<CustomField>
    <fullName>ReferredStudent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Referred Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tx_VisaStatus__c.field-meta.xml
<CustomField>
    <fullName>Tx_VisaStatus__c</fullName>
    <label>Visa Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F1</fullName>
            </value>
            <value>
                <fullName>H1B</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/classes/tx_StudentConsentFormGeneral.cls
public  class tx_StudentConsentFormGeneral{
    public Contact SelectedContact {get;set;}
    public Contact SelectedContact1 {get;set;}
    public boolean showTenantDetails {get;set;}
    public string studentEmail {get;set;}
    public boolean hideButtons {get;set;}
    public boolean showButtons {get;set;}
    
    public tx_StudentConsentFormGeneral(){
        showTenantDetails=false;
        SelectedContact=new Contact();
        
    }
    public PageReference cancel(){
        SelectedContact.recordtypeID=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        selectedContact.referredStudent__c=true;
        selectedContact.accountid=system.label.unknownAccountID;
        SelectedContact.lastName =SelectedContact.firstName + ' '+ SelectedContact.lastName;
        SelectedContact.firstName=null;
        insert selectedContact;
        
        Case c  = new Case();
        c.recordtypeid=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Taxation').getRecordTypeId(); 
        c.contactID=SelectedContact.id;
        c.Accountid=SelectedContact.accountid;
        c.subject= Date.Today().Year() + ' Taxation for - ' + SelectedContact.lastName;
        c.origin='Student Consent';
        c.status='Student Consent Rejection';
        c.tx_Contact_Email__c=SelectedContact.email;
        Insert c;
        PageReference pageRef = new PageReference('/apex/Tx_StudentConsentAcknowledgement');
        pageRef.setRedirect(true);
        return pageRef; 
    }
    
    public PageReference save(){
        
        SelectedContact.recordtypeID=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        selectedContact.referredStudent__c=true;
        selectedContact.accountid=system.label.unknownAccountID;
        SelectedContact.lastName =SelectedContact.firstName + ' '+ SelectedContact.lastName;
        SelectedContact.firstName=null;
        insert selectedContact;
        
        Case c  = new Case();
        c.recordtypeid=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Taxation').getRecordTypeId(); 
        c.contactID=SelectedContact.id;
        c.Accountid=SelectedContact.accountid;
        c.subject= Date.Today().Year() + ' Taxation for - ' + SelectedContact.lastName;
        c.origin='Student Consent';
        c.status='Student Consent Acceptance';
        c.tx_Contact_Email__c=SelectedContact.email;
        c.txVisaStatus__c=SelectedContact.Tx_VisaStatus__c;
        Insert c;
        
        PageReference pageRef = new PageReference('/apex/Tx_StudentConsentAcknowledgement');
        pageRef.setRedirect(true);
        return pageRef;      
    }
    
    
}