force-app/main/default/objects/Case/fields/tx_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>tx_Contact_Email__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/txContactMobilePhone__c.field-meta.xml
<CustomField>
    <fullName>txContactMobilePhone__c</fullName>
    <label>Contact Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/txVisaStatus__c.field-meta.xml
<CustomField>
    <fullName>txVisaStatus__c</fullName>
    <label>Visa Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TaxationJourneyStatus__c.field-meta.xml
<CustomField>
    <fullName>TaxationJourneyStatus__c</fullName>
    <label>Taxation Journey Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consent Form Shared</fullName>
            </value>
            <value>
                <fullName>Student Consent Acceptance</fullName>
            </value>
            <value>
                <fullName>Student Consent Rejection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Tx_VisaStatus__c.field-meta.xml
<CustomField>
    <fullName>Tx_VisaStatus__c</fullName>
    <label>Visa Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F1</fullName>
            </value>
            <value>
                <fullName>H1B</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/classes/tx_CaseTriggerHelper.cls
public class tx_CaseTriggerHelper {
    
    public void updateContactDetails(List<Case> lstCase)
    {
        Map<ID,String> mapContactEmail = new map<ID,String>();
        List<Contact> lstContact = new List<Contact>();
        For(Case c: lstCase)
        {
            IF(c.origin!=null && c.origin.equalsignorecase('Student Consent') && c.contactid!=null)
            {
                Contact con = new Contact();
                con.id=c.contactid;
                con.email=c.tx_Contact_Email__c;
                con.Tx_VisaStatus__c=c.txVisaStatus__c;
                con.TaxationJourneyStatus__c=c.status;
                con.mobilePhone=c.txContactMobilePhone__c;
                lstContact.add(con);
            }
        }
        
        if(lstContact.size()>0) update lstContact;
        
    }

}