force-app/main/default/objects/WhatsAppMessage__c/WhatsAppMessage__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Message</label>
    <nameField>
        <displayFormat>WM-{0000000}</displayFormat>
        <label>WhatsApp Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsAppMessage__c/fields/WhatsAppMessage__c.field-meta.xml
<CustomField>
    <fullName>WhatsAppMessage__c</fullName>
    <label>WhatsApp Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WhatsAppMessage__c/fields/WhatsAppMsgTemplate__c.field-meta.xml
<CustomField>
    <fullName>WhatsAppMsgTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WhatsApp Msg Template</label>
    <referenceTo>WhatsAppMsgTemplates__c</referenceTo>
    <relationshipLabel>WhatsApp Message</relationshipLabel>
    <relationshipName>WhatsApp_Message</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsAppMsgTemplates__c/WhatsAppMsgTemplates__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Msg Templates</label>
    <nameField>
        <displayFormat>WT-{0000000}</displayFormat>
        <label>WhatsApp Msg Templates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Msg Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/eTutorWhatsappMessageService.cls
public  class eTutorWhatsappMessageService{
    public WhatsAppMessage__c whatsAppMessage {get;set;}
    
 
    
    public eTutorWhatsappMessageService(){
       
       
        whatsAppMessage=new WhatsAppMessage__c();
      
        
    }
    public PageReference save(){
        
        
        Insert whatsAppMessage;
      
      //  PageReference pageRef = new PageReference('/apex/thankyoupage');
      //  pageRef.setRedirect(true);
        return null;      
    }
    public void showMessage()
    {
        List<WhatsAppMsgTemplates__c> temp = [select id, Message__c from WhatsAppMsgTemplates__c where id=:whatsAppMessage.WhatsAppMsgTemplate__c ];
        if(temp.size()>0)
        whatsAppMessage.WhatsAppMessage__c = temp[0].Message__c;
    }
   
}