force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/LogTime__c.field-meta.xml
<CustomField>
    <fullName>LogTime__c</fullName>
    <label>Log Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/SentToSlack__c.field-meta.xml
<CustomField>
    <fullName>SentToSlack__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to Slack</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ErrorHandler.cls
public class ErrorHandler {
    
    public static void logError(String className ,String methodName ,String description ,String stackTrace){
        ErrorLog__c  error = new ErrorLog__c ();
        error.ClassName__c  = className + ' ' +methodName;
        error.LogTime__c  = system.now();
        error.Description__c  = description;
        error.StackTrace__c  = stackTrace;
        error.SentToSlack__c=true;
        insert error;
    } 
   /* public static ErrorLog__c addError(String className ,String methodName ,String description ,String stackTrace) {
        ErrorLog__c  error = new ErrorLog__c ();
        error.ClassName__c  = className + ' ' +methodName;
        error.LogTime__c  = system.now();
        error.Description__c  = description;
        error.StackTrace__c  = stackTrace;
        return error;
    }
    
    public static void logErrors(List<ErrorLog__c> errList) {
        insert errList;
    }
    */
}