force-app/main/default/objects/Account/recordTypes/College_University.recordType-meta.xml
<RecordType>
    <fullName>College_University</fullName>
    <active>true</active>
    <label>College/University</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/College_University.recordType-meta.xml
<RecordType>
    <fullName>College_University</fullName>
    <active>true</active>
    <label>College/University</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/No_of_Modules__c.field-meta.xml
<CustomField>
    <fullName>No_of_Modules__c</fullName>
    <label>No of Modules</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Started</fullName>
                <default>true</default>
                <label>Not Yet Started</label>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/CRT.recordType-meta.xml
<RecordType>
    <fullName>CRT</fullName>
    <active>true</active>
    <label>CRT</label>
</RecordType>

force-app/main/default/objects/Course__c/recordTypes/Internship.recordType-meta.xml
<RecordType>
    <fullName>Internship</fullName>
    <active>true</active>
    <label>Internship</label>
</RecordType>

force-app/main/default/objects/CourseConnection__c/CourseConnection__c.object-meta.xml
<CustomObject>
    <label>CourseConnection</label>
    <nameField>
        <displayFormat>CC-{0}</displayFormat>
        <label>CourseConnection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CourseConnections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseConnection__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch1</fullName>
            </value>
            <value>
                <fullName>Batch2</fullName>
            </value>
            <value>
                <fullName>Batch3</fullName>
            </value>
            <value>
                <fullName>Batch4</fullName>
            </value>
            <value>
                <fullName>Batch5</fullName>
            </value>
            <value>
                <fullName>Batch6</fullName>
            </value>
            <value>
                <fullName>Batch7</fullName>
            </value>
            <value>
                <fullName>Batch8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CourseConnections</relationshipLabel>
    <relationshipName>CourseConnections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/CourseOffering__c.field-meta.xml
<CustomField>
    <fullName>CourseOffering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CourseOffering</label>
    <referenceTo>CourseOffering__c</referenceTo>
    <relationshipLabel>CourseConnections</relationshipLabel>
    <relationshipName>CourseConnections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Tutor</fullName>
            </value>
            <value>
                <fullName>Spock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/recordTypes/CRT.recordType-meta.xml
<RecordType>
    <fullName>CRT</fullName>
    <active>true</active>
    <label>CRT</label>
</RecordType>

force-app/main/default/objects/CourseConnection__c/recordTypes/Internship.recordType-meta.xml
<RecordType>
    <fullName>Internship</fullName>
    <active>true</active>
    <label>Internship</label>
</RecordType>

force-app/main/default/objects/CourseOffering__c/CourseOffering__c.object-meta.xml
<CustomObject>
    <label>CourseOffering</label>
    <nameField>
        <label>CourseOffering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CourseOfferings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseOffering__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch1</fullName>
            </value>
            <value>
                <fullName>Batch2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/collegeOrUniversity__c.field-meta.xml
<CustomField>
    <fullName>collegeOrUniversity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>college/University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CourseOfferings</relationshipLabel>
    <relationshipName>CourseOfferings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>CourseOfferings</relationshipLabel>
    <relationshipName>CourseOfferings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseOffering__c/recordTypes/CRT.recordType-meta.xml
<RecordType>
    <fullName>CRT</fullName>
    <active>true</active>
    <label>CRT</label>
</RecordType>

force-app/main/default/objects/CourseOffering__c/recordTypes/Internship.recordType-meta.xml
<RecordType>
    <fullName>Internship</fullName>
    <active>true</active>
    <label>Internship</label>
</RecordType>

force-app/main/default/objects/CourseProgress__c/CourseProgress__c.object-meta.xml
<CustomObject>
    <label>CourseProgress</label>
    <nameField>
        <displayFormat>CP-{0}</displayFormat>
        <label>CourseProgress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CourseProgresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseProgress__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/CourseConnection__c.field-meta.xml
<CustomField>
    <fullName>CourseConnection__c</fullName>
    <label>CourseConnection</label>
    <referenceTo>CourseConnection__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Available</fullName>
                <default>true</default>
                <label>Not Available</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/recordTypes/CRT.recordType-meta.xml
<RecordType>
    <fullName>CRT</fullName>
    <active>true</active>
    <label>CRT</label>
</RecordType>

force-app/main/default/objects/CourseProgress__c/recordTypes/Internship.recordType-meta.xml
<RecordType>
    <fullName>Internship</fullName>
    <active>true</active>
    <label>Internship</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/recordTypes/CRT.recordType-meta.xml
<RecordType>
    <fullName>CRT</fullName>
    <active>true</active>
    <label>CRT</label>
</RecordType>

force-app/main/default/objects/Program__c/recordTypes/Internship.recordType-meta.xml
<RecordType>
    <fullName>Internship</fullName>
    <active>true</active>
    <label>Internship</label>
</RecordType>

force-app/main/default/classes/UpdateModuleStatusOnCourseProgressTest.cls
@isTest
private class UpdateModuleStatusOnCourseProgressTest {

    @isTest
    static void myUnitTest() {
        
        System.debug('Starting test execution');

        Account university = new Account(
            Name = 'Test Account',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('College_University').getRecordTypeId()
        );
        insert university;
        System.debug('Inserted university: ' + university.Id);

        Program__c program = new Program__c(Name = 'Web Designing & Development');
        insert program;
        System.debug('Inserted program: ' + program.Id);

        Course__c course = new Course__c(
            Name = 'Test Course',
            Status__c = 'Completed',
            Program__c = program.Id,
            No_of_Modules__c = 5 
        );
        insert course;
        System.debug('Inserted course: ' + course.Id);

        CourseOffering__c courseOffering = new CourseOffering__c(
            Course__c = course.Id,
            collegeOrUniversity__c = university.Id,
            Project__c='Available'
        );
        insert courseOffering;
        System.debug('Inserted courseOffering: ' + courseOffering.Id);

        Contact student = new Contact(
            FirstName = 'Test',
            LastName = 'Student',
            Email = 'test@student.com',
            AccountId = university.Id
        );
        insert student;
        System.debug('Inserted student: ' + student.Id);

        CourseConnection__c courseConnection1 = new CourseConnection__c(
            Contact__c = student.Id,
            CourseOffering__c = courseOffering.Id,
            Type__c = 'Student',
            Batch__c = 'Batch1',
            RecordTypeId = Schema.SObjectType.CourseConnection__c.getRecordTypeInfosByDeveloperName().get('CRT').getRecordTypeId()
        );
        insert courseConnection1;
        System.debug('Inserted courseConnection1: ' + courseConnection1.Id);

        CourseConnection__c courseConnection2 = new CourseConnection__c(
            Contact__c = student.Id,
            CourseOffering__c = courseOffering.Id,
            Type__c = 'Student',
            Batch__c = 'Batch1',
            RecordTypeId = Schema.SObjectType.CourseConnection__c.getRecordTypeInfosByDeveloperName().get('Internship').getRecordTypeId()
        );
        insert courseConnection2;
        System.debug('Inserted courseConnection2: ' + courseConnection2.Id);

        CourseProgress__c cp = new CourseProgress__c(
            courseConnection__c = courseConnection1.Id
        );
        insert cp;
        System.debug('Inserted CourseProgress: ' + cp.Id);

        System.debug('Test execution completed');
    }
}