force-app/main/default/objects/Account/recordTypes/College_University.recordType-meta.xml
<RecordType>
    <fullName>College_University</fullName>
    <active>true</active>
    <label>College/University</label>
</RecordType>

force-app/main/default/objects/Chart_Colors__mdt/Chart_Colors__mdt.object-meta.xml
<CustomObject>
    <label>Chart Colors</label>
    <pluralLabel>Chart Colors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact/fields/APSCHE_Name__c.field-meta.xml
<CustomField>
    <fullName>APSCHE_Name__c</fullName>
    <label>APSCHE Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APSCHE 1</fullName>
            </value>
            <value>
                <fullName>APSCHE 2</fullName>
            </value>
            <value>
                <fullName>APSCHE 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/College_University.recordType-meta.xml
<RecordType>
    <fullName>College_University</fullName>
    <active>true</active>
    <label>College/University</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Started</fullName>
                <default>true</default>
                <label>Not Yet Started</label>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/CourseConnection__c.object-meta.xml
<CustomObject>
    <label>CourseConnection</label>
    <nameField>
        <displayFormat>CC-{0}</displayFormat>
        <label>CourseConnection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CourseConnections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseConnection__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch1</fullName>
            </value>
            <value>
                <fullName>Batch2</fullName>
            </value>
            <value>
                <fullName>Batch3</fullName>
            </value>
            <value>
                <fullName>Batch4</fullName>
            </value>
            <value>
                <fullName>Batch5</fullName>
            </value>
            <value>
                <fullName>Batch6</fullName>
            </value>
            <value>
                <fullName>Batch7</fullName>
            </value>
            <value>
                <fullName>Batch8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CourseConnections</relationshipLabel>
    <relationshipName>CourseConnections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/CourseOffering__c.field-meta.xml
<CustomField>
    <fullName>CourseOffering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CourseOffering</label>
    <referenceTo>CourseOffering__c</referenceTo>
    <relationshipLabel>CourseConnections</relationshipLabel>
    <relationshipName>CourseConnections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Tutor</fullName>
            </value>
            <value>
                <fullName>Spock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseOffering__c/CourseOffering__c.object-meta.xml
<CustomObject>
    <label>CourseOffering</label>
    <nameField>
        <label>CourseOffering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CourseOfferings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseOffering__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch1</fullName>
            </value>
            <value>
                <fullName>Batch2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/collegeOrUniversity__c.field-meta.xml
<CustomField>
    <fullName>collegeOrUniversity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>college/University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CourseOfferings</relationshipLabel>
    <relationshipName>CourseOfferings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>CourseOfferings</relationshipLabel>
    <relationshipName>CourseOfferings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/CourseProgress__c.object-meta.xml
<CustomObject>
    <label>CourseProgress</label>
    <nameField>
        <displayFormat>CP-{0}</displayFormat>
        <label>CourseProgress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CourseProgresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseProgress__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/CourseConnection__c.field-meta.xml
<CustomField>
    <fullName>CourseConnection__c</fullName>
    <label>CourseConnection</label>
    <referenceTo>CourseConnection__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Module_1_Status__c.field-meta.xml
<CustomField>
    <fullName>Module_1_Status__c</fullName>
    <label>Module 1 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Module_Option</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Module_2_Status__c.field-meta.xml
<CustomField>
    <fullName>Module_2_Status__c</fullName>
    <label>Module 2 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Module_Option</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Module_3_Status__c.field-meta.xml
<CustomField>
    <fullName>Module_3_Status__c</fullName>
    <label>Module 3 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Module_Option</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DashBoardCtrlTest.cls
@isTest
private class DashBoardCtrlTest {

    @isTest
    static void myUnitTest() {
        Account university = new Account(Name = 'Test Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('College_University').getRecordTypeId());
        insert university;

        Program__c program = new Program__c(Name = 'Web Designing & Development');
        insert program;

        Course__c course = new Course__c(Name = 'Test Course', Status__c = 'Completed',Program__c=program.Id);
        insert course;

        CourseOffering__c courseOffering = new CourseOffering__c(Course__c = course.Id, collegeOrUniversity__c = university.Id);
        insert courseOffering;

        Contact student = new Contact(FirstName = 'Test', LastName = 'Student', Email = 'test@student.com', AccountId = university.Id,APSCHE_Name__c='APSCHE 1');
        insert student;

        CourseConnection__c courseConnection = new CourseConnection__c(Contact__c = student.Id, CourseOffering__c = courseOffering.Id, Type__c = 'Student', Batch__c = 'Batch1');
        insert courseConnection;

        CourseProgress__c courseProgress = new CourseProgress__c(
            Student__c = student.Id,
            Module_1_Status__c = 'Completed',
            Module_2_Status__c = 'Not Applicable',
            Module_3_Status__c = 'Completed',
            CourseConnection__c = courseConnection.Id
        );
        insert courseProgress;
        String selectedUniversity = university.Id;
        String selectedBatch = 'Batch1';
        String selectedCourse = 'Android Studio';
        String selectedProgram = 'Web Designing & Development';
        String selectedModule = 'Module 1';
        String selectedApsche = 'APSCHE 1';
        String selectedCourseStatus = 'Completed';
        String selectedUDLabel = 'Avila';
        String selectedMentor = 'John';
        Boolean selectedCRTValue = true;
        String selectedYear='II';

        List<String> mentors= DashBoardCtrl.getMentors(selectedCRTValue);

        List<String> universities= DashBoardCtrl.getUniversities(selectedCRTValue,selectedMentor);
        List<AggregateResult> universityWiseData = DashBoardCtrl.getUniversityWiseData(selectedCRTValue,selectedMentor,selectedUniversity,selectedApsche);
        List<AggregateResult> universityWiseData2 = DashBoardCtrl.getUniversityWiseData(false,selectedMentor,'APSCHE',selectedApsche);
        List<AggregateResult> universityWiseData3 = DashBoardCtrl.getUniversityWiseData(false,selectedMentor,'APSCHE','');
        List<AggregateResult> universityWiseData4 = DashBoardCtrl.getUniversityWiseData(false,selectedMentor,selectedUniversity,'');
        
        List<Chart_Colors__mdt> result3= DashBoardCtrl.getChartColors();

        Map<String, Object> programWiseData1 = DashBoardCtrl.getProgramWiseData(selectedCRTValue,selectedUniversity,selectedMentor,selectedApsche,selectedUDLabel);
        Map<String, Object> programWiseData2 = DashBoardCtrl.getProgramWiseData(false,selectedUniversity,selectedMentor,'','');
        Map<String, Object> programWiseData3 = DashBoardCtrl.getProgramWiseData(false,'APSCHE',selectedMentor,selectedApsche,selectedUDLabel);
        Map<String, Object> programWiseData4 = DashBoardCtrl.getProgramWiseData(false,'APSCHE',selectedMentor,'',selectedUDLabel);

        List<Map<String, String>> CourseOptions1= DashBoardCtrl.getCourseOptions(selectedCRTValue,selectedMentor, selectedUDLabel, selectedUniversity, selectedProgram,selectedApsche);
        List<Map<String, String>> CourseOptions2= DashBoardCtrl.getCourseOptions(false,selectedMentor, selectedUDLabel, selectedUniversity, selectedProgram,'');
        List<Map<String, String>> CourseOptions3= DashBoardCtrl.getCourseOptions(false,selectedMentor, selectedUDLabel, 'APSCHE', selectedProgram,selectedApsche);
        List<Map<String, String>> CourseOptions4= DashBoardCtrl.getCourseOptions(false,selectedMentor, selectedUDLabel, 'APSCHE', selectedProgram,'');

        List<CourseProgress__c> ModuleWiseData1= DashBoardCtrl.getModuleWiseData(selectedCRTValue,selectedMentor,selectedUniversity,selectedBatch,selectedCourse,selectedProgram,selectedUDLabel);
        List<CourseProgress__c> ModuleWiseData2= DashBoardCtrl.getModuleWiseData(false,selectedMentor,selectedUniversity,selectedBatch,selectedCourse,selectedProgram,selectedUDLabel);
        List<CourseProgress__c> ModuleWiseData3= DashBoardCtrl.getModuleWiseData(false,selectedMentor,'APSCHE',selectedApsche,selectedCourse,selectedProgram,selectedUDLabel);
        List<CourseProgress__c> ModuleWiseData4= DashBoardCtrl.getModuleWiseData(false,selectedMentor,'APSCHE','',selectedCourse,selectedProgram,selectedUDLabel);
        
    }
}