force-app/main/default/objects/Account/recordTypes/College_University.recordType-meta.xml
<RecordType>
    <fullName>College_University</fullName>
    <active>true</active>
    <label>College/University</label>
</RecordType>

force-app/main/default/objects/Contact/fields/APSCHE__c.field-meta.xml
<CustomField>
    <fullName>APSCHE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>APSCHE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mentor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tutor__c.field-meta.xml
<CustomField>
    <fullName>Tutor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tutor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/College_University.recordType-meta.xml
<RecordType>
    <fullName>College_University</fullName>
    <active>true</active>
    <label>College/University</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/No_of_Modules__c.field-meta.xml
<CustomField>
    <fullName>No_of_Modules__c</fullName>
    <label>No of Modules</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Started</fullName>
                <default>true</default>
                <label>Not Yet Started</label>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/CourseConnection__c.object-meta.xml
<CustomObject>
    <label>CourseConnection</label>
    <nameField>
        <displayFormat>CC-{0}</displayFormat>
        <label>CourseConnection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CourseConnections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseConnection__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch1</fullName>
            </value>
            <value>
                <fullName>Batch2</fullName>
            </value>
            <value>
                <fullName>Batch3</fullName>
            </value>
            <value>
                <fullName>Batch4</fullName>
            </value>
            <value>
                <fullName>Batch5</fullName>
            </value>
            <value>
                <fullName>Batch6</fullName>
            </value>
            <value>
                <fullName>Batch7</fullName>
            </value>
            <value>
                <fullName>Batch8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/CourseOffering__c.field-meta.xml
<CustomField>
    <fullName>CourseOffering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CourseOffering</label>
    <referenceTo>CourseOffering__c</referenceTo>
    <relationshipLabel>CourseConnections</relationshipLabel>
    <relationshipName>CourseConnections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseOffering__c/CourseOffering__c.object-meta.xml
<CustomObject>
    <label>CourseOffering</label>
    <nameField>
        <label>CourseOffering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CourseOfferings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseOffering__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch1</fullName>
            </value>
            <value>
                <fullName>Batch2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>CourseOfferings</relationshipLabel>
    <relationshipName>CourseOfferings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CourseOfferings</relationshipLabel>
    <relationshipName>CourseOfferings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/CourseProgress__c.object-meta.xml
<CustomObject>
    <label>CourseProgress</label>
    <nameField>
        <displayFormat>CP-{0}</displayFormat>
        <label>CourseProgress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CourseProgresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseProgress__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/CourseConnection__c.field-meta.xml
<CustomField>
    <fullName>CourseConnection__c</fullName>
    <label>CourseConnection</label>
    <referenceTo>CourseConnection__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Module1_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Module1_Completion_Date__c</fullName>
    <label>Module1 Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Module2_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Module2_Completion_Date__c</fullName>
    <label>Module2 Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Module_1_Status__c.field-meta.xml
<CustomField>
    <fullName>Module_1_Status__c</fullName>
    <label>Module 1 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Module_Option</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Module_2_Status__c.field-meta.xml
<CustomField>
    <fullName>Module_2_Status__c</fullName>
    <label>Module 2 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Module_Option</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Module_3_Status__c.field-meta.xml
<CustomField>
    <fullName>Module_3_Status__c</fullName>
    <label>Module 3 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Module_Option</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Available</fullName>
                <default>true</default>
                <label>Not Available</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseProgress__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CourseProgresses</relationshipLabel>
    <relationshipName>CourseProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/University__c.field-meta.xml
<CustomField>
    <fullName>University__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MentorCourseProgressTrackerTest.cls
@isTest
private class MentorCourseProgressTrackerTest {

    @isTest
    static void myUnitTest() {
        Account university = new Account(Name = 'Avila', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('College_University').getRecordTypeId());
        insert university;

        Program__c program = new Program__c(Name = 'Test Program', Status__c = 'Active', University__c = university.Id);
        insert program;
        
        Course__c course = new Course__c(Name = 'Test Course', Status__c = 'Completed', Program__c = program.Id, No_of_Modules__c = 4);
        insert course;
        
        Contact mentor = new Contact(FirstName = 'Test', LastName = 'Mentor', AccountId = university.Id, Tutor__c = true, APSCHE__c = true);
        insert mentor;
        
        CourseOffering__c courseOffering = new CourseOffering__c(Course__c = course.Id, Mentor__c = mentor.Id, Batch__c = 'Batch1');
        insert courseOffering;

        CourseConnection__c courseConnection = new CourseConnection__c(CourseOffering__c=courseOffering.Id, Status__c='Active');
        insert courseConnection;

        Contact student = new Contact(FirstName = 'Test', LastName = 'Student', AccountId = university.Id, APSCHE__c = true);
        insert student;
        
        CourseProgress__c courseProgress = new CourseProgress__c(Student__c = student.Id, 
        Course__c = course.Id, Program__c = program.Id,
        CourseConnection__c=courseConnection.Id,Module_1_Status__c='Completed',
        Module_2_Status__c='Completed',Module_3_Status__c='Completed',Status__c='Active'
        
        
        );
        insert courseProgress;

        String selectedUniversity = university.Id;
        String selectedAPSCHE = ' ';        
        String selectedProgram = program.id;
        Integer totalModules = 4;
        String selectedMentor = mentor.id;
        String selectedCourse = course.Id ;
        Boolean selectedCRTValue = true;
        String selectedYear='II';

        MentorCourseProgressTracker.getMentors(selectedCRTValue);
        MentorCourseProgressTracker.getUniversities(selectedCRTValue,selectedMentor);
        MentorCourseProgressTracker.getPrograms(selectedCRTValue,selectedMentor,selectedUniversity,selectedAPSCHE,selectedYear);
        MentorCourseProgressTracker.getCourses(selectedCRTValue,selectedMentor,selectedUniversity,'',selectedProgram,selectedYear);
        MentorCourseProgressTracker.getCourses(selectedCRTValue,selectedMentor,'APSCHE',selectedAPSCHE,selectedProgram,selectedYear);
        MentorCourseProgressTracker.getData(selectedCRTValue,selectedMentor,'APSCHE', selectedAPSCHE, selectedProgram, selectedCourse,selectedYear);
        MentorCourseProgressTracker.getData(selectedCRTValue,selectedMentor,'APSCHE', '', selectedProgram, selectedCourse,selectedYear);
        MentorCourseProgressTracker.getData(selectedCRTValue,selectedMentor,selectedUniversity, '', selectedProgram, selectedCourse,selectedYear);
        MentorCourseProgressTracker.getIncompleteModuleStatuses(courseProgress.Id, totalModules);

        List<MentorCourseProgressTracker.Wrapper> wrappers = new List<MentorCourseProgressTracker.Wrapper>();

        MentorCourseProgressTracker.Wrapper wrap = new MentorCourseProgressTracker.Wrapper();
        wrap.Id = courseProgress.Id;
        wrap.serialNumber = 1;
        wrap.studentName = 'Test Student';
        wrap.collegeName = university.Name;
        wrap.apsche = 'APSCHE 1';
        wrap.batchNumber = 'Batch1';
        wrap.courseName = 'Test';
        wrap.totalModules = 4;
        wrap.modulesCompleted = '2';
        wrap.modulesInProgress = '2';
        wrap.selectedModuleNumbers = new List<String>{'Module 1', 'Module 2','Module 3','Module 4', 'Module 5','Module 6','Module 7', 'Module 8','Module 9','Module 10', 'Module 11','Module 12','Module 13', 'Module 14','Module 15'};
        wrap.status = 'Completed';
        wrap.project = 'Completed';
        wrap.comments = 'Test comments';
        wrap.moduleGrade = 'A';
        wrap.moduleFeedback = 'Good';
        wrap.courseFeedback = 'Good!';
        wrap.completedDate = Date.newInstance(2022, 1, 1);

        wrappers.add(wrap);

        Test.startTest();
        MentorCourseProgressTracker.updateCourseProgress(wrappers);
        Test.stopTest();

        CourseProgress__c updatedCourseProgress = [SELECT Id, Module_1_Status__c, Module_2_Status__c, Project__c, Comments__c, Module1_Completion_Date__c, Module2_Completion_Date__c FROM CourseProgress__c WHERE Id = :courseProgress.Id];
        
    }
}