force-app/main/default/objects/Discount_Coupon_Allocation__c/Discount_Coupon_Allocation__c.object-meta.xml
<CustomObject>
    <label>Discount Coupon Allocation</label>
    <nameField>
        <displayFormat>DCA-{00000}</displayFormat>
        <label>Discount Coupon Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Coupon Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/eTutorSyncResponse__c.field-meta.xml
<CustomField>
    <fullName>eTutorSyncResponse__c</fullName>
    <label>eTutorSyncResponse</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/eTutorSyncStatus__c.field-meta.xml
<CustomField>
    <fullName>eTutorSyncStatus__c</fullName>
    <label>eTutorSyncStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/LastSyncDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastSyncDateTime__c</fullName>
    <label>LastSyncDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/DiscountCoupons__c.object-meta.xml
<CustomObject>
    <label>Discount Coupons</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Discount Coupons Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DiscountCoupons__c/fields/eTutorSyncResponse__c.field-meta.xml
<CustomField>
    <fullName>eTutorSyncResponse__c</fullName>
    <label>eTutorSyncResponse</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/eTutorSyncStatus__c.field-meta.xml
<CustomField>
    <fullName>eTutorSyncStatus__c</fullName>
    <label>eTutorSyncStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/LastSyncDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastSyncDateTime__c</fullName>
    <label>LastSyncDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>Discount Coupons</relationshipLabel>
    <relationshipName>Discount_Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/eTutorDetails__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>eTutorDetails</label>
</CustomObject>

force-app/main/default/objects/eTutorDetails__c/fields/APIKEY__c.field-meta.xml
<CustomField>
    <fullName>APIKEY__c</fullName>
    <label>APIKEY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/DiscountCouponURL__c.field-meta.xml
<CustomField>
    <fullName>DiscountCouponURL__c</fullName>
    <label>DiscountCouponURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/PlagiairsmPaymentURL__c.field-meta.xml
<CustomField>
    <fullName>PlagiairsmPaymentURL__c</fullName>
    <label>PlagiairsmPaymentURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/PlagiairsmURL__c.field-meta.xml
<CustomField>
    <fullName>PlagiairsmURL__c</fullName>
    <label>PlagiairsmURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/WorkOrderPaymentURL__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderPaymentURL__c</fullName>
    <label>WorkOrderPaymentURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/WorkOrderURL__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderURL__c</fullName>
    <label>WorkOrderURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/eTutorSyncStatus__c.field-meta.xml
<CustomField>
    <fullName>eTutorSyncStatus__c</fullName>
    <label>eTutor Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/LastSyncDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastSyncDateTime__c</fullName>
    <label>Last Sync Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/WorkOrderPayment__c.object-meta.xml
<CustomObject>
    <label>Work Order Payment</label>
    <nameField>
        <displayFormat>WOP-{00000}</displayFormat>
        <label>Work Order Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Payment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderPayment__c/fields/eTutorSyncResponse__c.field-meta.xml
<CustomField>
    <fullName>eTutorSyncResponse__c</fullName>
    <label>eTutor Sync Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>Work Order Payment</relationshipLabel>
    <relationshipName>Work_Order_Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/eTutorAPIUtility.cls
public class eTutorAPIUtility {
    private final String url;
    private final String method;
    private final String body;
    
/*    public eTutorAPIUtility(String url, String method, String body) {
        this.url = url;
        this.method = method;
        this.body = body;
    }  
    public void executeeTutorCall() {
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod(method);
        req.setBody(body);
        Http http = new Http();
        HttpResponse res = http.send(req);
    }
   */ 
    @Future(callout=true)
    public Static void executeeTutorCallFuture(String method, String body,String objName,String recordID , String recordTypeName)
    {
        eTutorDetails__c et = eTutorDetails__c.getInstance();
        String url;
        IF(objName.equalsignorecase('workorder') && recordTypeName.equalsignorecase('Content Writing') )
        {
            url=et.WorkOrderURL__c;
        }
         IF(objName.equalsignorecase('workorder')&& recordTypeName.equalsignorecase('Plagiarism Check'))
        {
            url=et.PlagiairsmURL__c;
        }
        
        IF(objName.equalsignorecase('WorkOrderPayment') && recordTypeName.equalsignorecase('Content Writing'))
        {
            url=et.WorkOrderPaymentURL__c;
        }
        IF(objName.equalsignorecase('WorkOrderPayment') && recordTypeName.equalsignorecase('Plagiarism Check'))
        {
            url=et.PlagiairsmPaymentURL__c;
        }
         IF(objName.equalsignorecase('DiscountCoupon') || objName.equalsignorecase('DiscountCouponAllocation'))
        {
            url=et.DiscountCouponURL__c;
        }
        system.debug('body**' + body);
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod(method);
        req.setHeader('X-Etutorconnect-Api-Key', et.APIKEY__c);
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Accept', 'application/json');

        req.setBody(body);
        
        try {  
            Http http = new Http();
            HttpResponse httpResponse = http.send(req); 
            if (httpResponse.getStatusCode() == 200 ) {  
                System.debug('ERROR: '+ httpResponse.getBody());
               updateIntegrationStatus(objName,recordID,'Success', httpResponse.getBody());  
            } else {  
                System.debug('ERROR: '+ httpResponse.getBody());
               updateIntegrationStatus(objName,recordID,'Failed', httpResponse.getBody());  
               throw new CalloutException( httpResponse.getBody() );  
            }   
        } catch( System.Exception e) {  
            System.debug('ERROR: '+ e);  
            ErrorHandler.logError('eTutorAPIUtility',objName + 'id - '+recordID, e.getMessage(),e.getStackTraceString());
        }   
        
        
    }
    
    public static void updateIntegrationStatus(String objName,String recordID,String status, String responsebody)
    {
        
        IF(objName.equalsignorecase('workorder'))
        {
            workOrder__c wo = new workOrder__c();
            wo.eTutorSyncStatus__c = status;
            wo.eTutorSyncResponse__c = responsebody;
            wo.LastSyncDateTime__c = System.now();
            wo.id=recordID;
            update wo;
        }
        
        IF(objName.equalsignorecase('WorkOrderPayment'))
        {
            WorkOrderPayment__c wop = new WorkOrderPayment__c();
            wop.eTutorSyncStatus__c = status;
            wop.eTutorSyncResponse__c = responsebody;
            wop.LastSyncDateTime__c = System.now();
            wop.id=recordID;
            update wop;
        }
        
         IF(objName.equalsignorecase('DiscountCoupon'))
        {
            DiscountCoupons__c dc = new DiscountCoupons__c();
            dc.eTutorSyncStatus__c = status;
            dc.eTutorSyncResponse__c = responsebody;
            dc.LastSyncDateTime__c = System.now();
            dc.id=recordID;
            update dc;
        }
        
         IF(objName.equalsignorecase('DiscountCouponAllocation'))
        {
            Discount_Coupon_Allocation__c dc = new Discount_Coupon_Allocation__c();
            dc.eTutorSyncStatus__c = status;
            dc.eTutorSyncResponse__c = responsebody;
            dc.LastSyncDateTime__c = System.now();
            dc.id=recordID;
            update dc;
        }
        
    }
    
    
    
}