force-app/main/default/objects/Discount_Coupon_Allocation__c/Discount_Coupon_Allocation__c.object-meta.xml
<CustomObject>
    <label>Discount Coupon Allocation</label>
    <nameField>
        <displayFormat>DCA-{00000}</displayFormat>
        <label>Discount Coupon Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Coupon Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Discount_Coupons__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/Discount_Coupons__c.field-meta.xml
<CustomField>
    <fullName>Discount_Coupons__c</fullName>
    <label>Discount Coupons</label>
    <referenceTo>DiscountCoupons__c</referenceTo>
    <relationshipLabel>Discount Coupon Allocations</relationshipLabel>
    <relationshipName>Discount_Coupon_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/eTutorUserID__c.field-meta.xml
<CustomField>
    <fullName>eTutorUserID__c</fullName>
    <formula>Contact__r.eTutorUserID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>eTutorUserID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/StudentEmail__c.field-meta.xml
<CustomField>
    <fullName>StudentEmail__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/StudentNameFormula__c.field-meta.xml
<CustomField>
    <fullName>StudentNameFormula__c</fullName>
    <formula>Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentNameFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/StudentPhone__c.field-meta.xml
<CustomField>
    <fullName>StudentPhone__c</fullName>
    <formula>Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentPhone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/DiscountCoupons__c.object-meta.xml
<CustomObject>
    <label>Discount Coupons</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Discount Coupons Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DiscountCoupons__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic Coupon for First WO</fullName>
            </value>
            <value>
                <fullName>Generic Coupon for specific time</fullName>
            </value>
            <value>
                <fullName>Specific to a student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount  Percent/Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/DiscountCode__c.field-meta.xml
<CustomField>
    <fullName>DiscountCode__c</fullName>
    <formula>Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/eTutorUserID__c.field-meta.xml
<CustomField>
    <fullName>eTutorUserID__c</fullName>
    <formula>Contact__r.eTutorUserID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>eTutorUserID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <label>ExpiryDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Plagiarism</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentEmail__c.field-meta.xml
<CustomField>
    <fullName>StudentEmail__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentNameFormula__c.field-meta.xml
<CustomField>
    <fullName>StudentNameFormula__c</fullName>
    <formula>Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentNameFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentPhone__c.field-meta.xml
<CustomField>
    <fullName>StudentPhone__c</fullName>
    <formula>Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentPhone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiscountCouponAllocationTriggerHelper.cls
public class DiscountCouponAllocationTriggerHelper {
    
     public DiscountCouponAllocationTriggerHelper()
    {
        
    } 

    
     public void sendDiscountCouponsNotificationsToCustomer(List<Discount_Coupon_Allocation__c> newList,Map<ID,Discount_Coupon_Allocation__c> oldMap)
    {
        List<String> receiver = new List<String>();
         Set<ID> lstDisCouAll = new Set<ID>(); 
        
        For(Discount_Coupon_Allocation__c dc: newList )   
            
        { Discount_Coupon_Allocation__c old = new Discount_Coupon_Allocation__c();
           If(oldMap!=null)
           old = oldMap.get(dc.id);
             system.debug('**outsideloop ' + old);
            if((old!=null && dc.status__c.equals('Active') && old.Status__c!=dc.status__c) || (old==null && dc.status__c.equals('Active')))
            {
               system.debug('**Insideloop ' + old);
                lstDisCouAll.add(dc.id);
            }
            
        }
          For(Discount_Coupon_Allocation__c dc: [Select id,Name,Discount_Coupons__r.ExpiryDate__c,status__c,Discount_Coupons__r.Start_Date__c,Discount_Coupons__r.Category__c,Discount_Coupons__r.DiscountCode__c,Discount_Coupons__r.Description__c,Discount_Coupons__r.Discount_Type__c,Discount_Coupons__r.Discount_Amount__c,Discount_Coupons__r.Service__c, eTutorUserID__c,StudentEmail__c,StudentNameFormula__c,StudentPhone__c from Discount_Coupon_Allocation__c where id IN : lstDisCouAll] )
        {
           IF(dc.Discount_Coupons__r.Service__c.equalsignorecase('Assignment') ||dc.Discount_Coupons__r.Service__c.equalsignorecase('Plagiarism')  )
            {
                try
                {
                    Boolean sendToETutor=false;
                    Boolean sendSMS =false;
                    String SMSMessageTemplate;
                    receiver.add(dc.StudentEmail__c);
               
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorInitialPayment,dc.id);
                       
                        SMSMessageTemplate ='DiscountCoupon';
                    
                        sendDiscountCouponToETutor(dc.eTutorUserID__c,dc.Discount_Coupons__r.DiscountCode__c,dc.Discount_Coupons__r.Service__c,dc.Status__c,dc.id,'DiscountCouponAllocation',dc.Discount_Coupons__r.description__c,String.valueof(dc.Discount_Coupons__r.Discount_Amount__c),dc.Discount_Coupons__r.Discount_Type__c,String.valueof(dc.Discount_Coupons__r.Start_Date__c),String.valueof(dc.Discount_Coupons__r.ExpiryDate__c),dc.Discount_Coupons__r.category__c);
                   
                    
                        eTutorSMSNotificationsUtility.sendSMS(label.eTutorSMSMagicFromNumber, dc.StudentPhone__c, SMSMessageTemplate,dc.name,dc.id,dc.StudentNameFormula__c,null,null,null);
                    
                } 
                catch( System.Exception e) {  
                    System.debug('ERROR: '+ e);  
                    ErrorHandler.logError('DiscountCouponTriggerHelper','sendDiscountCouponsNotificationsToCustomer'+dc.id, e.getMessage(),e.getStackTraceString());
                }
                
            }  
        }
    }
    
    
    public void sendDiscountCouponToETutor(String eTutorUserID,String discountCode,String discountService,String Status,String recordID, String objName,String description,String discountValue, String discountType,String startDate,String expiryDate,String category)
    {
        Map<String,Object> msg = new Map<String,Object>();
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('discount_Code', discountCode);
        gen.writeStringField('discount_description', description);
        gen.writeStringField('discount_value', discountValue);
        gen.writeStringField('discount_type', discountType);
        gen.writeStringField('service',discountService);
        gen.writeStringField('status', Status);
         if(eTutorUserID!=null)gen.writeStringField('eTutor_ID', eTutorUserID);
        gen.writeStringField('startDate', startDate);
        gen.writeStringField('expiryDate', expiryDate);
        gen.writeStringField('category', category);
        gen.writeEndObject();
        eTutorAPIUtility.executeeTutorCallFuture('POST', gen.getAsString(),objName,recordID,null);
        
    }
    
    
    
}