force-app/main/default/objects/Discount_Coupon_Allocation__c/Discount_Coupon_Allocation__c.object-meta.xml
<CustomObject>
    <label>Discount Coupon Allocation</label>
    <nameField>
        <displayFormat>DCA-{00000}</displayFormat>
        <label>Discount Coupon Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Coupon Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Discount_Coupons__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Discount Coupon Allocations</relationshipLabel>
    <relationshipName>Discount_Coupon_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/Discount_Coupons__c.field-meta.xml
<CustomField>
    <fullName>Discount_Coupons__c</fullName>
    <label>Discount Coupons</label>
    <referenceTo>DiscountCoupons__c</referenceTo>
    <relationshipLabel>Discount Coupon Allocations</relationshipLabel>
    <relationshipName>Discount_Coupon_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/StudentEmail__c.field-meta.xml
<CustomField>
    <fullName>StudentEmail__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/StudentNameFormula__c.field-meta.xml
<CustomField>
    <fullName>StudentNameFormula__c</fullName>
    <formula>Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentNameFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/StudentPhone__c.field-meta.xml
<CustomField>
    <fullName>StudentPhone__c</fullName>
    <formula>Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentPhone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Coupon_Allocation__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>Discount Coupon Allocations</relationshipLabel>
    <relationshipName>Discount_Coupon_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/DiscountCoupons__c.object-meta.xml
<CustomObject>
    <label>Discount Coupons</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Discount Coupons Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DiscountCoupons__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic Coupon for First WO</fullName>
            </value>
            <value>
                <fullName>Generic Coupon for specific time</fullName>
            </value>
            <value>
                <fullName>Specific to a student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Discount Coupons</relationshipLabel>
    <relationshipName>Discount_Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentEmail__c.field-meta.xml
<CustomField>
    <fullName>StudentEmail__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentNameFormula__c.field-meta.xml
<CustomField>
    <fullName>StudentNameFormula__c</fullName>
    <formula>Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentNameFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/StudentPhone__c.field-meta.xml
<CustomField>
    <fullName>StudentPhone__c</fullName>
    <formula>Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentPhone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountCoupons__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>Discount Coupons</relationshipLabel>
    <relationshipName>Discount_Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SlackChannel__mdt/SlackChannel__mdt.object-meta.xml
<CustomObject>
    <label>SlackChannel</label>
    <pluralLabel>SlackChannel</pluralLabel>
</CustomObject>

force-app/main/default/objects/SlackChannel__mdt/fields/Slack_Url__c.field-meta.xml
<CustomField>
    <fullName>Slack_Url__c</fullName>
    <label>Slack Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/ActualStatus__c.field-meta.xml
<CustomField>
    <fullName>ActualStatus__c</fullName>
    <label>Actual Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>eTutorStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Work order</fullName>
                <default>true</default>
                <label>New Work order</label>
            </value>
            <value>
                <fullName>Assigned to Main Handler</fullName>
            </value>
            <value>
                <fullName>Main Handler Analysis</fullName>
            </value>
            <value>
                <fullName>Pending with customer for Initial payment</fullName>
            </value>
            <value>
                <fullName>Initial Payment Received</fullName>
            </value>
            <value>
                <fullName>Pending with Team member</fullName>
            </value>
            <value>
                <fullName>Team member open Queries</fullName>
            </value>
            <value>
                <fullName>Pending with Customer for Queires</fullName>
            </value>
            <value>
                <fullName>Main handler work review</fullName>
            </value>
            <value>
                <fullName>Main Handler review completed</fullName>
            </value>
            <value>
                <fullName>Work delivered</fullName>
            </value>
            <value>
                <fullName>Pending with Student</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>No Bandwidth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/DiscountCoupon__c.field-meta.xml
<CustomField>
    <fullName>DiscountCoupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount Coupons</label>
    <referenceTo>DiscountCoupons__c</referenceTo>
    <relationshipLabel>Work Order</relationshipLabel>
    <relationshipName>Work_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/eTutorStatus__c.field-meta.xml
<CustomField>
    <fullName>eTutorStatus__c</fullName>
    <label>eTutor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Order Received</fullName>
                <default>true</default>
                <label>Work Order Received</label>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Work in Progress</fullName>
            </value>
            <value>
                <fullName>Additional information Required</fullName>
            </value>
            <value>
                <fullName>Plagiarism Check Report Completed</fullName>
            </value>
            <value>
                <fullName>Work completed. Payment Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Plagiarism Free Report Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Plagiarism Free Report Payment Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/eTutorWorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>eTutorWorkOrderID__c</fullName>
    <externalId>true</externalId>
    <label>eTutor Work Order ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Final_Document__c.field-meta.xml
<CustomField>
    <fullName>Final_Document__c</fullName>
    <label>Final Document</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/FinalAmountAfterDiscount__c.field-meta.xml
<CustomField>
    <fullName>FinalAmountAfterDiscount__c</fullName>
    <formula>Price__c  -  DiscountOnAssignmentPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Amount After Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Initial_Amount_to_Pay__c.field-meta.xml
<CustomField>
    <fullName>Initial_Amount_to_Pay__c</fullName>
    <formula>IF(Price__c&gt;0,0.2 * Price__c,0.2* PlagiairsmFreeAmount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Initial Amount to Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/MainHandlerNameFormula__c.field-meta.xml
<CustomField>
    <fullName>MainHandlerNameFormula__c</fullName>
    <formula>MainHandler__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MainHandlerNameFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Order</relationshipLabel>
    <relationshipName>Work_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/StudentEmail__c.field-meta.xml
<CustomField>
    <fullName>StudentEmail__c</fullName>
    <formula>Student__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/StudentNameFormula__c.field-meta.xml
<CustomField>
    <fullName>StudentNameFormula__c</fullName>
    <formula>Student__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentNameFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/StudentPhone__c.field-meta.xml
<CustomField>
    <fullName>StudentPhone__c</fullName>
    <formula>Student__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkOrderTriggerHelper.cls
public class WorkOrderTriggerHelper {
    public Map<String,String> mapSlackUrl = new Map<String,String>();
    public String workOrderRecordTypeID;
    public String plagrismRecordTypeID;
    
    
    public WorkOrderTriggerHelper()
    {
        List<SlackChannel__mdt> slackUrl = [select id, Slack_Url__c , DeveloperName from SlackChannel__mdt ];
        for(SlackChannel__mdt slack: slackUrl)
        {
            mapSlackUrl.put(slack.DeveloperName,slack.Slack_Url__c);
        }  
        
        workOrderRecordTypeID = Schema.SObjectType.WorkOrder__c.getRecordTypeInfosByName().get('Content Writing').getRecordTypeId();
        
        plagrismRecordTypeID = Schema.SObjectType.WorkOrder__c.getRecordTypeInfosByName().get('Plagiarism Check').getRecordTypeId();
        
        
    }
    
    public void updateDiscountCouponAllocationStatus(List<WorkOrder__c> newList,Map<ID,WorkOrder__c> oldMap)
    {
        map<String,ID> mapStudentDiscount =  new Map<String,ID>();  
        Set<ID> setStudentId = new Set<ID>();
        Set<ID> discountId = new Set<ID>();
        Set<ID> workOrderId = new Set<ID>();
        List<Discount_Coupon_Allocation__c> lstNewDisAll =  new List<Discount_Coupon_Allocation__c>();
        List<Discount_Coupon_Allocation__c> lstUpdateDisAll =  new List<Discount_Coupon_Allocation__c>();
        
         For(WorkOrder__c wo: newList)
        {
            WorkOrder__c oldWo =  oldMap.get(wo.id);
            IF (wo.DiscountCoupon__c!=NULL && oldWo.DiscountCoupon__c==NULL )
            {
                workOrderId.add(wo.id);
            }
        }
        
        For(WorkOrder__c wo: [Select ID,Student__c,DiscountCoupon__c,DiscountCoupon__r.category__c from WorkOrder__c where ID IN:workOrderId])
        {
            WorkOrder__c oldWo =  oldMap.get(wo.id);
            IF (wo.DiscountCoupon__c!=NULL && oldWo.DiscountCoupon__c==NULL )
            {
                Discount_Coupon_Allocation__c disAll =  new Discount_Coupon_Allocation__c();
                if(wo.DiscountCoupon__r.category__c.equalsignorecase('Generic Coupon for specific time') || wo.DiscountCoupon__r.category__c.equalsignorecase('Generic Coupon for First WO'))
                {
                    disAll.contact__c=wo.Student__c;
                    disAll.Discount_Coupons__c=wo.DiscountCoupon__c;
                    disAll.Status__c='Redeemed';
                    disAll.work_order__c=wo.id;
                    lstNewDisAll.add(disAll);
                }
                if(wo.DiscountCoupon__r.category__c.equalsignorecase('Specific to a student'))
                {
                    setStudentId.add(wo.Student__c);
                    discountId.add(wo.DiscountCoupon__c);
                    mapStudentDiscount.put(wo.Student__c +':'+wo.DiscountCoupon__c,wo.Id);
                }
            }
            
        }
        IF(lstNewDisAll.size()>0)
            insert lstNewDisAll;
        
        For(Discount_Coupon_Allocation__c dc:[Select id,contact__c,Discount_Coupons__c,Status__c,work_order__c from Discount_Coupon_Allocation__c where contact__c IN:setStudentId AND Discount_Coupons__c IN:discountId])
        {
            Discount_Coupon_Allocation__c disAll =  new Discount_Coupon_Allocation__c();
            disAll.Status__c='Redeemed';
            disAll.work_order__c=mapStudentDiscount.get(dc.contact__c +':'+dc.Discount_Coupons__c);
            disAll.ID=dc.id;
            lstUpdateDisAll.add(disAll);
        }
        
        IF(lstUpdateDisAll.size()>0)
            update lstUpdateDisAll;
    }
  
    public void validateData(List<WorkOrder__c> newList)
    {
        
        For(WorkOrder__c wo: newList)
        {
            IF(wo.recordtypeid==workOrderRecordTypeID)
            {
                IF (wo.eTutorStatus__c.equalsignorecase('Payment Pending') && wo.Price__c==null )
                    
                {
                    wo.addError('Please enter the Price');
                }
                IF (wo.eTutorStatus__c.equalsignorecase('Completed') && wo.final_document__c==null )
                    
                {
                    wo.addError('Please update the final document URL');
                }
                
            }
            
            
        }
        
    }
    public void sendNewWorkOrderNotificationsToCustomer(List<WorkOrder__c> newList)
    {
        List<String> receiver = new List<String>(); 
        For(WorkOrder__c wo: newList)
        {
            
            IF(wo.recordtypeid==workOrderRecordTypeID)
            {
                IF (wo.eTutorStatus__c.equalsignorecase('Work order Received'))
                {
                    receiver.add(wo.StudentEmail__c);
                    eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorWorkOrderCreationAck,wo.id);
                    
                    eTutorSMSNotificationsUtility.sendSMS(label.eTutorSMSMagicFromNumber, wo.StudentPhone__c, 'WorkorderReceived',wo.name,wo.id,wo.StudentNameFormula__c,wo.eTutorWorkOrderID__c,wo.MainHandlerNameFormula__c,null);
                    
                }
            }
        }
        
    }
    public void sendNewWorkOrderNotificationsToSlack(List<WorkOrder__c> newList)
    {
        Map<String,Object> msg = new Map<String,Object>();
        String channelName;
        Boolean sendToSlack=false;
        For(WorkOrder__c wo: newList)
        {
            IF(wo.recordtypeid==workOrderRecordTypeID)
            {
                String message; 
                IF (wo.actualStatus__c.equalsignorecase('New Work order') )
                {
                    message =  'Hello, ' + '\n' ; 
                    message = message+ 'You have received a work order '+wo.name +' from Student '+wo.StudentNameFormula__c +'.' + '\n' ; 
                    message= message +'Please check the requirements and assign it to a respective Main Handler Name.'  + '\n';
                    msg.put('text', message );
                    
                    channelName='eTutorManager';
                    sendToSlack=true;
                    
                }
                if(sendToSlack)
                {
                    msg.put('mrkdwn', true);
                    String body = JSON.serialize(msg); 
                    eTutorSlackNotificationsUtility.executeSlackCallTrigger(mapSlackUrl.get(channelName), 'POST', body);
                } 
            }
            
        }
    }
    public void sendWorkOrderUpdateNotificationsToCustomer(List<WorkOrder__c> newList,Map<ID,WorkOrder__c> oldMap)
    {
        List<String> receiver = new List<String>();
        Boolean discountApplied=False;
        
        For(WorkOrder__c wo: newList)
        {
            IF(wo.recordtypeid==workOrderRecordTypeID)
            {
                try
                {
                    Boolean sendToETutor=false;
                    Boolean sendSMS =false;
                    String SMSMessageTemplate;
                    WorkOrder__c oldWo =  oldMap.get(wo.id);
                    receiver.add(wo.StudentEmail__c);
                    
                    IF (wo.DiscountCoupon__c!=NULL && oldWo.DiscountCoupon__c==NULL && wo.FinalAmountAfterDiscount__c<wo.price__c)
                    {
                        sendToETutor=true;
                        discountApplied=true;
                    }
                    
                    
                    
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Payment Pending') && !oldWo.eTutorStatus__c.equalsignorecase('Payment Pending'))
                        
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorInitialPayment,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='PaymentPending';
                    }
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Work in Progress') && !oldWo.eTutorStatus__c.equalsignorecase('Work in Progress'))
                        
                    {
                        sendToETutor=true;
                    }
                    
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Additional information Required') && !oldWo.eTutorStatus__c.equalsignorecase('Additional information Required'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorAdditionalInformationRequired,wo.id);
                        sendToETutor=true; 
                        sendSMS =True;
                        SMSMessageTemplate ='AdditionalInformationRequired'; 
                    }
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Work completed. Payment pending') && !oldWo.eTutorStatus__c.equalsignorecase('Work completed. Payment pending'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorWorkCompletedPaymentPending,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='WorkCompletedPaymentPending';               
                    }
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Completed') && !oldWo.eTutorStatus__c.equalsignorecase('Completed'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorWorkCompleted,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='Completed';
                    }
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Declined') && !oldWo.eTutorStatus__c.equalsignorecase('Declined'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorDeclined,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='Declined';
                    }
                    
                    IF(sendToETutor)
                    {
                        sendWorkOrderUpdatesToETutor(String.valueof(wo.Price__c),String.valueof(wo.Initial_Amount_to_Pay__c),wo.eTutorWorkOrderID__c,wo.eTutorStatus__c,'WorkOrder',String.valueof(wo.ID),wo.MainHandlerNameFormula__c,wo.Final_Document__c,'Content Writing',String.valueof(discountApplied),String.valueof(wo.DiscountOnAssignmentPrice__c),String.valueof(wo.FinalAmountAfterDiscount__c));
                    }
                    
                    IF(sendSMS) 
                    {
                        eTutorSMSNotificationsUtility.sendSMS(label.eTutorSMSMagicFromNumber, wo.StudentPhone__c, SMSMessageTemplate,wo.name,wo.id,wo.StudentNameFormula__c,wo.eTutorWorkOrderID__c,wo.MainHandlerNameFormula__c,null);
                    }
                } 
                catch( System.Exception e) {  
                    System.debug('ERROR: '+ e);  
                    ErrorHandler.logError('WorkOrderTriggerHelper','sendWorkOrderUpdateNotificationsToCustomer'+wo.id, e.getMessage(),e.getStackTraceString());
                }
                
            }  
        }
        
    }
    public void sendWorkOrderUpdateNotificationsToSlack(List<WorkOrder__c> newList,Map<ID,WorkOrder__c> oldMap)
    {
        Map<String,Object> msg = new Map<String,Object>();
        String channelName;
        Boolean sendToSlack=false;
        For(WorkOrder__c wo: newList)
        {
            IF(wo.recordtypeid==workOrderRecordTypeID)
            {
                WorkOrder__c oldWo =  oldMap.get(wo.id);
                String message;
                IF (wo.actualStatus__c.equalsignorecase('Assigned to Main Handler') && !oldWo.actualStatus__c.equalsignorecase('Assigned to Main Handler'))
                {
                    message =  'Hello ' +wo.MainHandlerNameFormula__c +','+ '\n' ; 
                    message = message+ 'A new work order '+wo.name +' from Student '+wo.StudentNameFormula__c +' has been assigned to you. ' + '\n' ; 
                    message= message +'Please check the student requirements and complete it as per the deadlines.'  + '\n';
                    
                    msg.put('text', message);
                    channelName=wo.MainHandlerNameFormula__c;
                    sendToSlack=true;   
                }
                
                if(sendToSlack)
                {
                    msg.put('mrkdwn', true);
                    String body = JSON.serialize(msg); 
                    eTutorSlackNotificationsUtility.executeSlackCallTrigger(mapSlackUrl.get(channelName), 'POST', body);
                } 
            }
        }
        
    }
    
    public void sendWorkOrderUpdatesToETutor(String workOrderAmount,String workorderinitialamount,String workOrderId,String status,String objName,String recordID,String workOrderMainHandlerName, String outputFileURL, String recordTypeName, String discountApplied,String discountValue,String finalAmountAfterDiscount)
    {
        Map<String,Object> msg = new Map<String,Object>();
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('workOrderId', workOrderId);
        gen.writeStringField('workOrderStatus', status);
        gen.writeStringField('workOrderMainHandlerName',workOrderMainHandlerName);
        if(outputFileURL!=null)gen.writeStringField('outputFileURL',outputFileURL );
        gen.writeStringField('discountApplied',discountApplied);
        if(workOrderAmount!=null)gen.writeStringField('workOrderAmount', workOrderAmount);
        gen.writeStringField('workOrderInitialAmount',workorderinitialamount);
        gen.writeStringField('discountvalue',discountValue);
        gen.writeStringField('finalAmountAfterDiscount',finalAmountAfterDiscount);
        
        
        gen.writeEndObject();
        eTutorAPIUtility.executeeTutorCallFuture('POST', gen.getAsString(),objName,recordID,recordTypeName);
        
    }
     
    public void sendNewPlagrismNotificationsToCustomer(List<WorkOrder__c> newList)
    {
        List<String> receiver = new List<String>(); 
        For(WorkOrder__c wo: newList)
        {
            
            IF(wo.recordtypeid==plagrismRecordTypeID)
            {
                IF (wo.eTutorStatus__c.equalsignorecase('Work order Received'))
                {
                    receiver.add(wo.StudentEmail__c);
                    eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorPlagiarismCreationAck,wo.id);
                    
                    eTutorSMSNotificationsUtility.sendSMS(label.eTutorSMSMagicFromNumber, wo.StudentPhone__c, 'PlagiarismOrderReceived',wo.name,wo.id,wo.StudentNameFormula__c,wo.eTutorWorkOrderID__c,wo.MainHandlerNameFormula__c,null);
                    
                }
            }
        }
        
    }
    public void sendNewPlagrismNotificationsToSlack(List<WorkOrder__c> newList)
    {
        Map<String,Object> msg = new Map<String,Object>();
        String channelName;
        Boolean sendToSlack=false;
        For(WorkOrder__c wo: newList)
        {
            IF(wo.recordtypeid==plagrismRecordTypeID)
            {
                String message; 
                IF (wo.actualStatus__c.equalsignorecase('New Work order') )
                {
                    message =  'Hello, ' + '\n' ; 
                    message = message+ 'You have received Plagiarism check work order '+wo.name +' from Student '+wo.StudentNameFormula__c +'.' + '\n' ; 
                    message= message +'Please check the requirements and assign it to a respective Main Handler Name.'  + '\n';
                    msg.put('text', message );
                    
                    channelName='eTutorManager';
                    sendToSlack=true;
                    
                }
                if(sendToSlack)
                {
                    msg.put('mrkdwn', true);
                    String body = JSON.serialize(msg); 
                    eTutorSlackNotificationsUtility.executeSlackCallTrigger(mapSlackUrl.get(channelName), 'POST', body);
                } 
            }
            
        }
    }
    public void sendplagrismUpdateNotificationsToCustomer(List<WorkOrder__c> newList,Map<ID,WorkOrder__c> oldMap)
    {
        List<String> receiver = new List<String>();
        Boolean discountApplied=False;
        For(WorkOrder__c wo: newList)
        {
            IF(wo.recordtypeid==plagrismRecordTypeID)
            {
                try
                {
                    Boolean sendToETutor=false;
                    Boolean sendSMS =false;
                    String SMSMessageTemplate;
                    WorkOrder__c oldWo =  oldMap.get(wo.id);
                    receiver.add(wo.StudentEmail__c);
                    
                      IF (wo.DiscountCoupon__c!=NULL && oldWo.DiscountCoupon__c==NULL )
                    {
                        sendToETutor=true;
                        discountApplied=true;
                    }
                    
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Plagiarism Free Report Payment Pending') && !oldWo.eTutorStatus__c.equalsignorecase('Plagiarism Free Report Payment Pending'))
                        
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorInitialPayment,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='PaymentPending';
                    }
                    
                    IF ((wo.eTutorStatus__c.equalsignorecase('Work in Progress') && !oldWo.eTutorStatus__c.equalsignorecase('Work in Progress')) ||
                        ( wo.PlagiarismCheckAmount__c!=oldWo.PlagiarismCheckAmount__c) ||
                        ( wo.PlagiairsmFreeAmount__c!=oldWo.PlagiairsmFreeAmount__c ) ||         
                        ( wo.PromptMessage__c!=oldWo.PromptMessage__c )||
                        ( wo.PlagiarismCheckURLDocument__c!=oldWo.PlagiarismCheckURLDocument__c )||
                        ( wo.Final_Document__c!=oldWo.Final_Document__c )||
                        ( wo.Plagiarism_more_than_20__c==true && oldWo.Plagiarism_more_than_20__c!=true ))
                    {
                        sendToETutor=true; 
                    }
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Plagiarism Check Report Completed') && !oldWo.eTutorStatus__c.equalsignorecase('Plagiarism Check Report Completed'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorplagiarismcheckCompleted,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='PlagiarismCheckReportCompleted';
                    }
                    
                    IF (wo.Plagiarism_more_than_20__c==true  && wo.eTutorStatus__c.equalsignorecase('Plagiarism Check Report Completed') && !oldWo.eTutorStatus__c.equalsignorecase('Plagiarism Check Report Completed'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorplagiarismcheck20,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='PlagiarismCheckReportCompleted20';
                    }
                    
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Additional information Required') && !oldWo.eTutorStatus__c.equalsignorecase('Additional information Required'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorAdditionalInformationRequired,wo.id);
                        sendToETutor=true; 
                        sendSMS =True;
                        SMSMessageTemplate ='AdditionalInformationRequired';  
                    }
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Work completed. Payment pending') && !oldWo.eTutorStatus__c.equalsignorecase('Work completed. Payment pending'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorWorkCompletedPaymentPending,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='WorkCompletedPaymentPending';               
                    }
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Plagiarism Free Report Completed') && !oldWo.eTutorStatus__c.equalsignorecase('Plagiarism Free Report Completed'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorWorkCompleted,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='Completed';
                    }
                    
                    IF (wo.eTutorStatus__c.equalsignorecase('Declined') && !oldWo.eTutorStatus__c.equalsignorecase('Declined'))
                    {
                        eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorDeclined,wo.id);
                        sendToETutor=true;
                        sendSMS =True;
                        SMSMessageTemplate ='Declined';
                    }
                    
                    IF(sendToETutor)
                    {
                        sendplagrismUpdatesToETutor(String.valueof(wo.PlagiarismCheckAmount__c),String.valueof(wo.PlagiairsmFreeAmount__c),wo.PromptMessage__c,wo.eTutorWorkOrderID__c,wo.eTutorStatus__c,'WorkOrder',String.valueof(wo.ID),wo.MainHandlerNameFormula__c,wo.Final_Document__c,wo.PlagiarismCheckURLDocument__c,'Plagiarism Check',String.valueof(wo.Plagiarism_more_than_20__c),String.valueof(discountApplied),String.valueof(wo.Discount_on_Plagarism_Price__c),String.valueof(wo.Final_Plagarism_amount_after_discount__c) );
                     }
                    
                    IF(sendSMS) 
                    {
                        eTutorSMSNotificationsUtility.sendSMS(label.eTutorSMSMagicFromNumber, wo.StudentPhone__c, SMSMessageTemplate,wo.name,wo.id,wo.StudentNameFormula__c,wo.eTutorWorkOrderID__c,wo.MainHandlerNameFormula__c,null);
                    }
                } 
                catch( System.Exception e) {  
                    System.debug('ERROR: '+ e);  
                    ErrorHandler.logError('WorkOrderTriggerHelper','sendWorkOrderUpdateNotificationsToCustomer'+wo.id, e.getMessage(),e.getStackTraceString());
                }
                
            }  
        }
        
    }
    public void sendplagrismUpdateNotificationsToSlack(List<WorkOrder__c> newList,Map<ID,WorkOrder__c> oldMap)
    {
        Map<String,Object> msg = new Map<String,Object>();
        String channelName;
        Boolean sendToSlack=false;
        For(WorkOrder__c wo: newList)
        {
            IF(wo.recordtypeid==plagrismRecordTypeID)
            {
                WorkOrder__c oldWo =  oldMap.get(wo.id);
                String message;
                IF (wo.actualStatus__c.equalsignorecase('Assigned to Main Handler') && !oldWo.actualStatus__c.equalsignorecase('Assigned to Main Handler'))
                {
                    message =  'Hello ' +wo.MainHandlerNameFormula__c +','+ '\n' ; 
                    message = message+ 'A new Plagiarism check work order '+wo.name +' from Student '+wo.StudentNameFormula__c +' has been assigned to you. ' + '\n' ; 
                    message= message +'Please check the Plagiarism using turnitin and upload the document.'  + '\n';
                    
                    msg.put('text', message);
                    channelName=wo.MainHandlerNameFormula__c;
                    sendToSlack=true;   
                }
                IF (wo.Plagiairsm_Free_Report_Requested__c==true && oldWo.Plagiairsm_Free_Report_Requested__c==false)
                {
                    message =  'Hello ' +wo.MainHandlerNameFormula__c +','+ '\n' ; 
                    message = message+ 'For Plagiarism check work order '+wo.name +' from Student '+wo.StudentNameFormula__c +', ' + '\n' ; 
                    message= message +'The student has requested for a plagiarism free document. Kindly check the document and complete it as per the requirements.'  + '\n';
                    
                    msg.put('text', message);
                    channelName=wo.MainHandlerNameFormula__c;
                    sendToSlack=true;   
                }
                
                if(sendToSlack)
                {
                    msg.put('mrkdwn', true);
                    String body = JSON.serialize(msg); 
                    eTutorSlackNotificationsUtility.executeSlackCallTrigger(mapSlackUrl.get(channelName), 'POST', body);
                } 
            }
        }
        
    }
    
    public void sendplagrismUpdatesToETutor(String plagiairsmCheckAmount,String plagiairsmFreeAmount,String promtMessage,String workOrderId,String status,String objName,String recordID,String workOrderMainHandlerName, String outputFileURL ,String PlagiarismCheckURLDocument , String recordTypeName, String PlagiarismMoreThan20, String discountApplied,String discountValue,String finalAmountAfterDiscount)
    {
        Map<String,Object> msg = new Map<String,Object>();
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('workOrderId', workOrderId);
        gen.writeStringField('workOrderStatus', status);
        gen.writeStringField('workOrderMainHandlerName',workOrderMainHandlerName);
        if(promtMessage!=null) gen.writeStringField('promtMessage',promtMessage);
        gen.writeStringField('plagiairsmCheckAmount',plagiairsmCheckAmount);
        gen.writeStringField('plagiairsmFreeAmount',plagiairsmFreeAmount);
        if(outputFileURL!=null)gen.writeStringField('PlagiarismFreeDocument',outputFileURL );
        if(PlagiarismCheckURLDocument!=null)gen.writeStringField('PlagiarismCheckURLDocument',PlagiarismCheckURLDocument );
        if(PlagiarismMoreThan20.equalsignorecase('true') )gen.writeStringField('PlagiarismMoreThan20',PlagiarismMoreThan20 );
        
        gen.writeStringField('discountApplied',discountApplied);
        gen.writeStringField('discountvalue',discountValue);
        gen.writeStringField('finalAmountAfterDiscount',finalAmountAfterDiscount);
       
        gen.writeEndObject();
        eTutorAPIUtility.executeeTutorCallFuture('POST', gen.getAsString(),objName,recordID,recordTypeName);
        
    }
    
    
    
}