force-app/main/default/objects/Chart_Colors__mdt/Chart_Colors__mdt.object-meta.xml
<CustomObject>
    <label>Chart Colors</label>
    <pluralLabel>Chart Colors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact/fields/CRT__c.field-meta.xml
<CustomField>
    <fullName>CRT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CRT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/No_of_Modules__c.field-meta.xml
<CustomField>
    <fullName>No_of_Modules__c</fullName>
    <label>No of Modules</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Started</fullName>
                <default>true</default>
                <label>Not Yet Started</label>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/CourseConnection__c.object-meta.xml
<CustomObject>
    <label>CourseConnection</label>
    <nameField>
        <displayFormat>CC-{0}</displayFormat>
        <label>CourseConnection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CourseConnections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseConnection__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CourseConnections</relationshipLabel>
    <relationshipName>CourseConnections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/CourseOffering__c.field-meta.xml
<CustomField>
    <fullName>CourseOffering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CourseOffering</label>
    <referenceTo>CourseOffering__c</referenceTo>
    <relationshipLabel>CourseConnections</relationshipLabel>
    <relationshipName>CourseConnections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Tutor</fullName>
            </value>
            <value>
                <fullName>Spock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseConnection__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <inlineHelpText>Select a Year to which this is Applicable.</inlineHelpText>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseOffering__c/CourseOffering__c.object-meta.xml
<CustomObject>
    <label>CourseOffering</label>
    <nameField>
        <label>CourseOffering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CourseOfferings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseOffering__c/fields/collegeOrUniversity__c.field-meta.xml
<CustomField>
    <fullName>collegeOrUniversity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>college/University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CourseOfferings</relationshipLabel>
    <relationshipName>CourseOfferings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseOffering__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>CourseOfferings</relationshipLabel>
    <relationshipName>CourseOfferings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TPODashboardCtrlTest.cls
@isTest
private class TPODashboardCtrlTest {

    @isTest
    static void myUnitTest() {
        Account university = new Account(
            Name = 'Test University'
        );
        insert university;

        Program__c program = new Program__c(Name = 'Web Designing & Development');
        insert program;

        Course__c course = new Course__c(
            Name = 'Test Course', 
            Status__c = 'Completed', 
            Program__c = program.Id,
            No_of_Modules__c=3
        );
        insert course;

        CourseOffering__c courseOffering = new CourseOffering__c(
            Course__c = course.Id, 
            collegeOrUniversity__c = university.Id
        );
        insert courseOffering;

        Contact student = new Contact(
            FirstName = 'Test', 
            LastName = 'Student', 
            Email = 'test@student.com', 
            AccountId = university.Id,
            CRT__c = true 
        );
        insert student;

        CourseConnection__c courseConnection = new CourseConnection__c(
            Contact__c = student.Id, 
            CourseOffering__c = courseOffering.Id, 
            Type__c = 'Student', 
            Status__c = 'Active',
            Year__c = 'II' 
        );
        insert courseConnection;


        String selectedUniversity = university.Name; 
        String selectedCourse = 'Test Course';
        String selectedProgram = 'Web Designing & Development';
        String selectedYear = 'II';

        Test.startTest();
        
        Map<String, Object> universitiesResult = TPODashboardCtrl.getUniversities();
        // System.assertNotEquals(null, universitiesResult, 'Expected universitiesResult not to be null');
        // System.assert(universitiesResult.containsKey('universityStudentCounts'), 'Expected universityStudentCounts key in result');
        Map<String, Integer> universityStudentCounts = (Map<String, Integer>) universitiesResult.get('universityStudentCounts');
        // System.assertEquals(1, universityStudentCounts.get(selectedUniversity), 'Expected student count for university');

        Map<String, Integer> yearWiseStudentCountResult = TPODashboardCtrl.getYearWiseStudentCount(selectedUniversity, selectedYear);
        // System.assertNotEquals(null, yearWiseStudentCountResult, 'Expected yearWiseStudentCountResult not to be null');
        // System.assertEquals(1, yearWiseStudentCountResult.get(selectedYear), 'Expected student count for selected year');

        List<Chart_Colors__mdt> chartColorsResult = TPODashboardCtrl.getChartColors();
        // System.assertNotEquals(null, chartColorsResult, 'Expected chartColorsResult not to be null');

        Map<String, Object> programsResult = TPODashboardCtrl.getPrograms(selectedUniversity, selectedYear);
        // System.assertNotEquals(null, programsResult, 'Expected programsResult not to be null');
        // System.assert(programsResult.containsKey('programWiseStudentCount'), 'Expected programWiseStudentCount key in result');
        Map<String, Integer> programWiseStudentCount = (Map<String, Integer>) programsResult.get('programWiseStudentCount');
        // System.assertEquals(1, programWiseStudentCount.get(selectedProgram), 'Expected student count for program');

        List<String> coursesResult = TPODashboardCtrl.getCourses(selectedUniversity, selectedYear, selectedProgram);
        // System.assertNotEquals(null, coursesResult, 'Expected coursesResult not to be null');
        // System.assertEquals(1, coursesResult.size(), 'Expected number of courses');
        // System.assertEquals('Test Course', coursesResult[0], 'Expected course name');

        Map<String, Object> moduleWiseDataResult = TPODashboardCtrl.getModuleWiseData(selectedUniversity, selectedYear, selectedCourse, selectedProgram);
        // System.assertNotEquals(null, moduleWiseDataResult, 'Expected moduleWiseDataResult not to be null');
        // System.assertEquals(1, moduleWiseDataResult.size(), 'Expected number of module progress records');
        // System.assertEquals('Not Yet Started', moduleWiseDataResult[0].Module_1_Status__c, 'Expected Module 1 status');
        
        
        System.debug('Universities Result: ' + universitiesResult);
        System.debug('Year Wise Student Count Result: ' + yearWiseStudentCountResult);
        System.debug('Chart Colors Result: ' + chartColorsResult);
        System.debug('Programs Result: ' + programsResult);
        System.debug('Courses Result: ' + coursesResult);
        System.debug('Module Wise Data Result: ' + moduleWiseDataResult);

        Test.stopTest();
    }
}