force-app/main/default/objects/SlackChannel__mdt/SlackChannel__mdt.object-meta.xml
<CustomObject>
    <label>SlackChannel</label>
    <pluralLabel>SlackChannel</pluralLabel>
</CustomObject>

force-app/main/default/objects/SlackChannel__mdt/fields/Slack_Url__c.field-meta.xml
<CustomField>
    <fullName>Slack_Url__c</fullName>
    <label>Slack Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/StudentEmail__c.field-meta.xml
<CustomField>
    <fullName>StudentEmail__c</fullName>
    <formula>Student__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/StudentPhone__c.field-meta.xml
<CustomField>
    <fullName>StudentPhone__c</fullName>
    <formula>Student__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/WorkOrderPayment__c.object-meta.xml
<CustomObject>
    <label>Work Order Payment</label>
    <nameField>
        <displayFormat>WOP-{00000}</displayFormat>
        <label>Work Order Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Payment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderPayment__c/fields/eTutorPaymentID__c.field-meta.xml
<CustomField>
    <fullName>eTutorPaymentID__c</fullName>
    <externalId>true</externalId>
    <label>eTutor Payment ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/eTutorWorkOrderIDFormula__c.field-meta.xml
<CustomField>
    <fullName>eTutorWorkOrderIDFormula__c</fullName>
    <formula>WorkOrder__r.eTutorWorkOrderID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>eTutorWorkOrderIDFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/MainHandlerName__c.field-meta.xml
<CustomField>
    <fullName>MainHandlerName__c</fullName>
    <formula>WorkOrder__r.MainHandlerNameFormula__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MainHandlerName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/StudentEmail__c.field-meta.xml
<CustomField>
    <fullName>StudentEmail__c</fullName>
    <formula>WorkOrder__r.StudentEmail__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/StudentName__c.field-meta.xml
<CustomField>
    <fullName>StudentName__c</fullName>
    <formula>WorkOrder__r.Student__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/StudentPhone__c.field-meta.xml
<CustomField>
    <fullName>StudentPhone__c</fullName>
    <formula>WorkOrder__r.StudentPhone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StudentPhone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>Work Order Payment</relationshipLabel>
    <relationshipName>Work_Order_Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/WorkOrder_RecordType__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder_RecordType__c</fullName>
    <formula>WorkOrder__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WorkOrder RecordType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/WorkOrderName__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderName__c</fullName>
    <formula>WorkOrder__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WorkOrderName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkOrderPaymentTriggerHelper.cls
public class WorkOrderPaymentTriggerHelper {
    public Map<String,String> mapSlackUrl = new Map<String,String>();
    
    public WorkOrderPaymentTriggerHelper()
    {
        List<SlackChannel__mdt> slackUrl = [select id, Slack_Url__c , DeveloperName from SlackChannel__mdt ];//where DeveloperName='sk_google_sheet_data' ];
        for(SlackChannel__mdt slack: slackUrl)
        {
            mapSlackUrl.put(slack.DeveloperName,slack.Slack_Url__c);
        }   
    }
    
    public void sendNewPaymentNotificationsToCustomer(List<WorkOrderPayment__c> newList)
    {
        List<String> receiver = new List<String>(); 
        
        For(WorkOrderPayment__c wo: newList)
        {
            try
            {
                IF (wo.Status__c.equalsignorecase('Confirmed'))
                {
                    receiver.add(wo.StudentEmail__c);
                    eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorInitialPaymentReceivedAck,wo.id);
                    eTutorSMSNotificationsUtility.sendSMS(label.eTutorSMSMagicFromNumber, wo.StudentPhone__c,'PaymentReceived',wo.name,wo.WorkOrder__c,wo.StudentName__c,wo.eTutorWorkOrderIDFormula__c,null,wo.Amount__c);
                    
                }
            } catch( System.Exception e) {  
                System.debug('ERROR: '+ e);  
                ErrorHandler.logError('WorkOrderPaymentTriggerHelper','sendNewPaymentNotificationsToCustomer'+wo.id, e.getMessage(),e.getStackTraceString());
            }
        }
        
        
    }
    public void sendNewPaymentNotificationsToSlack(List<WorkOrderPayment__c> newList)
    {
        Map<String,Object> msg = new Map<String,Object>();
        String channelName;
        Boolean sendToSlack=false;
        
        For(WorkOrderPayment__c wo: newList)
        {
            String message;
            message =  'Hello ' +wo.MainHandlerName__c +','+ '\n' ; 
            message = message+ 'Payment has been received for the work order '+wo.WorkOrderName__c +' from Student '+wo.StudentName__c +'.' + '\n' ; 
            message= message +'Please validate the transaction and perform next steps'  + '\n';
            msg.put('text', message);
            msg.put('mrkdwn', true);
            String body = JSON.serialize(msg); 
            eTutorSlackNotificationsUtility.executeSlackCallTrigger(mapSlackUrl.get(wo.MainHandlerName__c), 'POST', body);
        }
    }
    public void sendPaymentUpdateNotificationsToCustomer(List<WorkOrderPayment__c> newList,Map<ID,WorkOrderPayment__c> oldMap)
    {
        List<String> receiver = new List<String>();
        For(WorkOrderPayment__c wo: newList)
        {
            try{
                
                Boolean sendToETutor=false;
                WorkOrderPayment__c oldWo =  oldMap.get(wo.id);
                receiver.add(wo.StudentEmail__c);
                IF (wo.Amount__c!=null && wo.Status__c.equalsignorecase('Confirmed') && oldWo.Status__c.equalsignorecase('Pending Confirmation'))
                    
                {
                    eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,label.eTutorInitialPaymentReceivedAck,wo.id);
                    sendToETutor=true;
                    eTutorSMSNotificationsUtility.sendSMS(label.eTutorSMSMagicFromNumber, wo.StudentPhone__c,'PaymentReceived',wo.name,wo.WorkOrder__c,wo.StudentName__c,wo.eTutorWorkOrderIDFormula__c,null,wo.Amount__c);
                    
                }
                IF(sendToETutor)
                {
                    String amount = String.valueof(wo.Amount__c); 
                    Map<String,Object> msg = new Map<String,Object>();
                    JSONGenerator gen = JSON.createGenerator(true);
                    gen.writeStartObject();
                    gen.writeStringField('ETutorPaymentID__c', wo.eTutorPaymentID__c);
                    gen.writeStringField('Amount__c',amount);
                    gen.writeStringField('Status__c', wo.Status__c);
                    gen.writeEndObject();
                    eTutorAPIUtility.executeeTutorCallFuture('POST', gen.getAsString(),'WorkOrderPayment',String.valueof(wo.ID),wo.WorkOrder_RecordType__c); 
                }
                
            } catch( System.Exception e) {  
                System.debug('ERROR: '+ e);  
                ErrorHandler.logError('WorkOrderPaymentTriggerHelper','sendPaymentUpdateNotificationsToCustomer - ' + wo.ID, e.getMessage(),e.getStackTraceString());
            } 
        }
        
        
    }
    
}