force-app/main/default/objects/Contact/fields/eTutorUserID__c.field-meta.xml
<CustomField>
    <fullName>eTutorUserID__c</fullName>
    <externalId>true</externalId>
    <label>eTutor User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/eTutor.recordType-meta.xml
<RecordType>
    <fullName>eTutor</fullName>
    <active>true</active>
    <label>eTutor</label>
</RecordType>

force-app/main/default/classes/ContactTriggerHelper.cls
public class ContactTriggerHelper {
    
    public void sendNeweTutorStudentWelcomeEmail(List<Contact> newList)
    {
        List<String> receiver = new List<String>(); 
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('eTutor').getRecordTypeId();

        For(Contact c: newList)
        {
            IF (c.Status__c.equalsignorecase('Active')&& c.eTutorUserID__c!=null && contactRecordTypeId==c.recordtypeid)
            {
                receiver.add(c.email);
                eTutorEmailNotificationsUtility emailNotification =  new eTutorEmailNotificationsUtility(receiver,'00X1g0000020aj8',c.id);
                
            }
        }
        
    }

}