force-app/main/default/objects/Contact/recordTypes/eTutor.recordType-meta.xml
<RecordType>
    <fullName>eTutor</fullName>
    <active>true</active>
    <label>eTutor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/ActualStatus__c.field-meta.xml
<CustomField>
    <fullName>ActualStatus__c</fullName>
    <label>Actual Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>eTutorStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Work order</fullName>
                <default>true</default>
                <label>New Work order</label>
            </value>
            <value>
                <fullName>Assigned to Main Handler</fullName>
            </value>
            <value>
                <fullName>Main Handler Analysis</fullName>
            </value>
            <value>
                <fullName>Pending with customer for Initial payment</fullName>
            </value>
            <value>
                <fullName>Initial Payment Received</fullName>
            </value>
            <value>
                <fullName>Pending with Team member</fullName>
            </value>
            <value>
                <fullName>Team member open Queries</fullName>
            </value>
            <value>
                <fullName>Pending with Customer for Queires</fullName>
            </value>
            <value>
                <fullName>Main handler work review</fullName>
            </value>
            <value>
                <fullName>Main Handler review completed</fullName>
            </value>
            <value>
                <fullName>Work delivered</fullName>
            </value>
            <value>
                <fullName>Pending with Student</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>No Bandwidth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/eTutorStatus__c.field-meta.xml
<CustomField>
    <fullName>eTutorStatus__c</fullName>
    <label>eTutor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Order Received</fullName>
                <default>true</default>
                <label>Work Order Received</label>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Work in Progress</fullName>
            </value>
            <value>
                <fullName>Additional information Required</fullName>
            </value>
            <value>
                <fullName>Plagiarism Check Report Completed</fullName>
            </value>
            <value>
                <fullName>Work completed. Payment Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Plagiarism Free Report Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Plagiarism Free Report Payment Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/eTutorWorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>eTutorWorkOrderID__c</fullName>
    <externalId>true</externalId>
    <label>eTutor Work Order ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Final_Document__c.field-meta.xml
<CustomField>
    <fullName>Final_Document__c</fullName>
    <label>Final Document</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/MainHandler__c.field-meta.xml
<CustomField>
    <fullName>MainHandler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Handler/Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Order (Main Handler)</relationshipLabel>
    <relationshipName>Work_Order1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/TeamMember__c.field-meta.xml
<CustomField>
    <fullName>TeamMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Order (Team Member)</relationshipLabel>
    <relationshipName>Work_Order2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityClassTest.cls
@isTest
public class UtilityClassTest {
    
    public static testmethod void testMethod1()
    {
        account eTutor_Students = new account();
        eTutor_Students.name = 'eTutor_Students';
        insert eTutor_Students;
        account SirianProject = new account();
        SirianProject.name = 'SirianProject';
        insert SirianProject; 
        
        contact mainHandler = new contact();
        mainHandler.lastname='Kalyani_eTutor';
        mainHandler.email='Kalyani_eTutor@abc.com';
        mainHandler.recordtypeid= Schema.SObjectType.contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        mainHandler.AccountId=SirianProject.id;
        insert mainHandler;
        contact student = new contact();
        student.lastname='student';
        student.email='student@abc.com';
        student.recordtypeid= Schema.SObjectType.contact.getRecordTypeInfosByName().get('eTutor').getRecordTypeId();
        student.AccountId=eTutor_Students.id;
        insert student;
        
        
        Task t = new Task();
        t.OwnerId = UserInfo.getUserId();
        t.Subject='Donni';
        t.Status='Not Started';
        t.Priority='Normal';
        insert t;  
        
        ErrorHandler.logerror('test' ,'test' ,'test' ,'test');
        
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockClass());   
        test.startTest();
        WorkOrder__c wo = new WorkOrder__c();
        
        wo.Subject__c = 'test';
        wo.Price__c=200;
        wo.Final_Document__c='abc.com';
        wo.eTutorStatus__c='Work Order Received';
        wo.ActualStatus__c ='New Work order';
        wo.MainHandler__c=mainHandler.id;
        wo.TeamMember__c=mainHandler.id;
        wo.eTutorWorkOrderID__c='123';
        insert wo;
        
        
        
        RestRequest req = new RestRequest(); 
        req.addParameter('workorderID',wo.id);
        req.addParameter('name','test');
        String fileData = 'This ';
        String fileDateBase64 = EncodingUtil.base64Encode(Blob.valueOf(fileData));
        
        req.requestBody=Blob.valueof(JSON.serialize(fileDateBase64));
      
        RestResponse res = new RestResponse();             
        req.requestURI = '/services/apexrest/DocumentUploadBase64/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response= res;
        DocumentUploadBase64.uploadDocument();
      
        
        
         test.stopTest();   
        
        
        
        
    }
}