force-app/main/default/objects/Contact/recordTypes/eTutor.recordType-meta.xml
<RecordType>
    <fullName>eTutor</fullName>
    <active>true</active>
    <label>eTutor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/eTutorDetails__c/eTutorDetails__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>eTutorDetails</label>
</CustomObject>

force-app/main/default/objects/eTutorDetails__c/fields/APIKEY__c.field-meta.xml
<CustomField>
    <fullName>APIKEY__c</fullName>
    <label>APIKEY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/PlagiairsmPaymentURL__c.field-meta.xml
<CustomField>
    <fullName>PlagiairsmPaymentURL__c</fullName>
    <label>PlagiairsmPaymentURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/PlagiairsmURL__c.field-meta.xml
<CustomField>
    <fullName>PlagiairsmURL__c</fullName>
    <label>PlagiairsmURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/WorkOrderPaymentURL__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderPaymentURL__c</fullName>
    <label>WorkOrderPaymentURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/eTutorDetails__c/fields/WorkOrderURL__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderURL__c</fullName>
    <label>WorkOrderURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/ActualStatus__c.field-meta.xml
<CustomField>
    <fullName>ActualStatus__c</fullName>
    <label>Actual Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>eTutorStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Work order</fullName>
                <default>true</default>
                <label>New Work order</label>
            </value>
            <value>
                <fullName>Assigned to Main Handler</fullName>
            </value>
            <value>
                <fullName>Main Handler Analysis</fullName>
            </value>
            <value>
                <fullName>Pending with customer for Initial payment</fullName>
            </value>
            <value>
                <fullName>Initial Payment Received</fullName>
            </value>
            <value>
                <fullName>Pending with Team member</fullName>
            </value>
            <value>
                <fullName>Team member open Queries</fullName>
            </value>
            <value>
                <fullName>Pending with Customer for Queires</fullName>
            </value>
            <value>
                <fullName>Main handler work review</fullName>
            </value>
            <value>
                <fullName>Main Handler review completed</fullName>
            </value>
            <value>
                <fullName>Work delivered</fullName>
            </value>
            <value>
                <fullName>Pending with Student</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>No Bandwidth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/eTutorStatus__c.field-meta.xml
<CustomField>
    <fullName>eTutorStatus__c</fullName>
    <label>eTutor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Order Received</fullName>
                <default>true</default>
                <label>Work Order Received</label>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Work in Progress</fullName>
            </value>
            <value>
                <fullName>Additional information Required</fullName>
            </value>
            <value>
                <fullName>Plagiarism Check Report Completed</fullName>
            </value>
            <value>
                <fullName>Work completed. Payment Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Plagiarism Free Report Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Plagiarism Free Report Payment Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/eTutorWorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>eTutorWorkOrderID__c</fullName>
    <externalId>true</externalId>
    <label>eTutor Work Order ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Final_Document__c.field-meta.xml
<CustomField>
    <fullName>Final_Document__c</fullName>
    <label>Final Document</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/MainHandler__c.field-meta.xml
<CustomField>
    <fullName>MainHandler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Handler/Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Order (Main Handler)</relationshipLabel>
    <relationshipName>Work_Order1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/TeamMember__c.field-meta.xml
<CustomField>
    <fullName>TeamMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Order (Team Member)</relationshipLabel>
    <relationshipName>Work_Order2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/WorkOrderPayment__c.object-meta.xml
<CustomObject>
    <label>Work Order Payment</label>
    <nameField>
        <displayFormat>WOP-{00000}</displayFormat>
        <label>Work Order Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Payment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderPayment__c/fields/eTutorPaymentID__c.field-meta.xml
<CustomField>
    <fullName>eTutorPaymentID__c</fullName>
    <externalId>true</externalId>
    <label>eTutor Payment ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderPayment__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>Work Order Payment</relationshipLabel>
    <relationshipName>Work_Order_Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WorkOrderTriggerTest.cls
@isTest
public class WorkOrderTriggerTest {
    
    public static testmethod void testMethod1()
    {
        account eTutor_Students = new account();
        eTutor_Students.name = 'eTutor_Students';
        insert eTutor_Students;
        account SirianProject = new account();
        SirianProject.name = 'eTutor Staff';
        insert SirianProject; 
        
        contact mainHandler = new contact();
        mainHandler.lastname='Kalyani_eTutor';
        mainHandler.email='Kalyani_eTutor@abc.com';
        mainHandler.recordtypeid= Schema.SObjectType.contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        mainHandler.AccountId=SirianProject.id;
        insert mainHandler;
        contact student = new contact();
        student.lastname='student';
        student.email='student@abc.com';
        student.recordtypeid= Schema.SObjectType.contact.getRecordTypeInfosByName().get('eTutor').getRecordTypeId();
        student.AccountId=eTutor_Students.id;
        insert student;
        
        eTutorDetails__c customSetting= new eTutorDetails__c();
        customSetting.WorkOrderURL__c='abc.com';
        customSetting.WorkOrderPaymentURL__c='abc.com';
        customSetting.APIKEY__c='test';
        insert customSetting;
        
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockClass());   
        test.startTest();
        WorkOrder__c wo = new WorkOrder__c();
        
        wo.Subject__c = 'test';
        wo.Price__c=200;
        wo.Final_Document__c='abc.com';
        wo.eTutorStatus__c='Work Order Received';
        wo.ActualStatus__c ='New Work order';
        wo.MainHandler__c=mainHandler.id;
        wo.TeamMember__c=mainHandler.id;
        wo.eTutorWorkOrderID__c='123';
        wo.recordtypeid= Schema.SObjectType.WorkOrder__c.getRecordTypeInfosByName().get('Content Writing').getRecordTypeId();
        insert wo;
        
        wo.eTutorStatus__c='Work Order Received';
        wo.ActualStatus__c='Assigned to Main Handler';
        update wo;
        
        wo.eTutorStatus__c='Payment Pending';
        wo.ActualStatus__c='Pending with customer for Initial payment';
        update wo;
        
        WorkOrderPayment__c wop = new WorkOrderPayment__c();
        wop.Amount__c=100;
        wop.Status__c='Confirmed';
        wop.WorkOrder__c=wo.id;
        wop.eTutorPaymentID__c='123';
        insert wop;
        
        WorkOrderPayment__c wop1 = new WorkOrderPayment__c();
        wop1.Amount__c=100;
        wop1.Status__c='Pending Confirmation';
        wop1.WorkOrder__c=wo.id;
         wop1.eTutorPaymentID__c='1234';
        insert wop1;
        wop1.Status__c='Confirmed';
        update wop1;
        
        
        
        wo.eTutorStatus__c='Work in Progress';
        wo.ActualStatus__c='Pending with Team member';
        update wo;
        wo.eTutorStatus__c='Work in Progress';
        wo.ActualStatus__c='Team member open Queries';
        update wo;
        wo.eTutorStatus__c='Work in Progress';
        wo.ActualStatus__c='Main handler work review';
        update wo;
        
        wo.eTutorStatus__c='Additional information Required';
        wo.ActualStatus__c='Pending with Customer for Queires';
        update wo;
        
        wo.eTutorStatus__c='Work completed. Payment pending';
        wo.ActualStatus__c='Main Handler review completed';
        update wo;
        wo.eTutorStatus__c='Completed';
        wo.ActualStatus__c='Work delivered';
        update wo;
        
        test.stopTest();   
    }
     public static testmethod void testMethod2()
    {
        account eTutor_Students = new account();
        eTutor_Students.name = 'eTutor_Students';
        insert eTutor_Students;
        account SirianProject = new account();
        SirianProject.name = 'eTutor Staff';
        insert SirianProject; 
        
        contact mainHandler = new contact();
        mainHandler.lastname='Kalyani_eTutor';
        mainHandler.email='Kalyani_eTutor@abc.com';
        mainHandler.recordtypeid= Schema.SObjectType.contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        mainHandler.AccountId=SirianProject.id;
        insert mainHandler;
        contact student = new contact();
        student.lastname='student';
        student.email='student@abc.com';
        student.recordtypeid= Schema.SObjectType.contact.getRecordTypeInfosByName().get('eTutor').getRecordTypeId();
        student.AccountId=eTutor_Students.id;
        insert student;
        
        eTutorDetails__c customSetting= new eTutorDetails__c();
        customSetting.WorkOrderURL__c='abc.com';
        customSetting.WorkOrderPaymentURL__c='abc.com';
        customSetting.APIKEY__c='test';
        customSetting.PlagiairsmPaymentURL__c='abc.com';
         customSetting.PlagiairsmURL__c='abc.com';
        insert customSetting;
        
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockClass());   
        test.startTest();
        WorkOrder__c wo = new WorkOrder__c();
        
        wo.Subject__c = 'test';
        wo.Price__c=200;
        wo.Final_Document__c='abc.com';
        wo.eTutorStatus__c='Work Order Received';
        wo.ActualStatus__c ='New Work order';
        wo.MainHandler__c=mainHandler.id;
        wo.TeamMember__c=mainHandler.id;
        wo.eTutorWorkOrderID__c='123';
        wo.recordtypeid= Schema.SObjectType.WorkOrder__c.getRecordTypeInfosByName().get('Plagiarism Check').getRecordTypeId();
        insert wo;
        
        wo.eTutorStatus__c='Work Order Received';
        //wo.ActualStatus__c='Assigned to Main Handler';
        update wo;
        
        wo.eTutorStatus__c='Work completed. Payment Pending';
        //wo.ActualStatus__c='Pending with customer for Initial payment';
        update wo;
        
        WorkOrderPayment__c wop = new WorkOrderPayment__c();
        wop.Amount__c=100;
        wop.Status__c='Confirmed';
        wop.WorkOrder__c=wo.id;
        wop.eTutorPaymentID__c='123';
        insert wop;
        
        WorkOrderPayment__c wop1 = new WorkOrderPayment__c();
        wop1.Amount__c=100;
        wop1.Status__c='Pending Confirmation';
        wop1.WorkOrder__c=wo.id;
         wop1.eTutorPaymentID__c='1234';
        insert wop1;
        wop1.Status__c='Confirmed';
        update wop1;
        
        
        
        wo.eTutorStatus__c='Work in Progress';
        //wo.ActualStatus__c='Pending with Team member';
        update wo;
                
        wo.eTutorStatus__c='Additional information Required';
        
        update wo;
        
        
        wo.eTutorStatus__c='Plagiarism Free Report Completed';
       
        update wo;
        
        test.stopTest();   
    }
}